Repository AztecProtocol/aztec-packages, pull requests merged in 2023-08, with the labels that each got.

#1348 refactor: Renaming storage getters
  yarn-project/aztec-node/src/aztec-node/http-node.test.ts
  yarn-project/aztec-node/src/aztec-node/http-node.ts
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/aztec-rpc/src/aztec_rpc_server/aztec_rpc_server.ts
  yarn-project/aztec.js/src/aztec_rpc_client/wallet.ts
  yarn-project/rollup-provider/src/app.ts
  yarn-project/types/src/interfaces/aztec-node.ts
  yarn-project/types/src/interfaces/aztec_rpc.ts
Labels: refactor, devex

#1272 feat(noir-contracts): `Option<T>` for get_notes
  yarn-project/acir-simulator/src/client/client_execution_context.ts
  yarn-project/acir-simulator/src/client/private_execution.test.ts
  yarn-project/acir-simulator/src/client/unconstrained_execution.test.ts
  yarn-project/noir-contracts/src/contracts/ecdsa_account_contract/src/ecdsa_public_key_note.nr
  yarn-project/noir-contracts/src/contracts/escrow_contract/src/address_note.nr
  yarn-project/noir-contracts/src/contracts/pending_commitments_contract/src/main.nr
  yarn-project/noir-contracts/src/contracts/pokeable_token_contract/src/address_note.nr
  yarn-project/noir-contracts/src/contracts/pokeable_token_contract/src/main.nr
  yarn-project/noir-contracts/src/contracts/pokeable_token_contract/src/storage.nr
  yarn-project/noir-contracts/src/contracts/schnorr_multi_key_account_contract/src/public_key_note.nr
  yarn-project/noir-contracts/src/contracts/zk_token_contract/src/claim_note.nr
  yarn-project/noir-libs/easy-private-state/src/easy_private_state.nr
  yarn-project/noir-libs/noir-aztec/src/note/lifecycle.nr
  yarn-project/noir-libs/noir-aztec/src/note/note_getter.nr
  yarn-project/noir-libs/noir-aztec/src/note/note_getter_options.nr
  yarn-project/noir-libs/noir-aztec/src/note/note_interface.nr
  yarn-project/noir-libs/noir-aztec/src/oracle/notes.nr
  yarn-project/noir-libs/noir-aztec/src/state_vars/set.nr
  yarn-project/noir-libs/noir-aztec/src/types.nr
  yarn-project/noir-libs/noir-aztec/src/types/option.nr
  yarn-project/noir-libs/value-note/src/balance_utils.nr
  yarn-project/noir-libs/value-note/src/filter.nr
  yarn-project/noir-libs/value-note/src/utils.nr
  yarn-project/noir-libs/value-note/src/value_note.nr
Labels: feature

#1369 feat: Celer benchmark
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/hash/benchmarks/CMakeLists.txt
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/hash/benchmarks/celer/CMakeLists.txt
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/hash/benchmarks/celer/sha256.bench.cpp
Labels: crypto

#1219 feat: New stdlib Transcript
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/transcript/transcript.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/transcript/trancript.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/transcript/transcript.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/utility/utility.hpp
Labels: crypto

#1353 feat: Initial cheatcode `loadPublic`
  yarn-project/end-to-end/src/cheat_codes.ts
  yarn-project/end-to-end/src/cross_chain/test_harness.ts
  yarn-project/end-to-end/src/e2e_cheat_codes.test.ts
  yarn-project/end-to-end/src/e2e_cross_chain_messaging.test.ts
  yarn-project/end-to-end/src/e2e_lending_contract.test.ts
  yarn-project/end-to-end/src/e2e_public_cross_chain_messaging.test.ts
  yarn-project/end-to-end/src/e2e_public_to_private_messaging.test.ts
  yarn-project/end-to-end/src/e2e_public_token_contract.test.ts
  yarn-project/end-to-end/src/uniswap_trade_on_l1_from_l2.test.ts
  yarn-project/end-to-end/src/utils.ts
Labels: devex

#1384 fix: Fixed a failing test and added a small fuzzer
  circuits/cpp/barretenberg/cpp/src/barretenberg/common/fuzzer.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_translator_circuit_builder.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_translator_circuit_builder.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_translator_circuit_builder.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_translator_mini.fuzzer.cpp
Labels: crypto

#1373 chore: Split SumcheckRound into Prover/Verifier classes
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck_round.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck_round.test.cpp
Labels: crypto

#1454 fix: yarn install in canary
  bootstrap.sh
Labels: fix, devops

#1471 chore: disable fft functions for polynomials instantiated on Grumpkin
  circuits/cpp/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fr.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/ecc/fields/field.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/plonk/proof_system/verifier/verifier.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/polynomials/polynomial.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/polynomials/polynomial.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/polynomials/polynomial_arithmetic.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/polynomials/polynomial_arithmetic.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/polynomials/polynomial_arithmetic.test.cpp
Labels: crypto

#1488 feat: Honk recursive verifier Pt. 1
  circuits/cpp/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/bn254.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/ecc/curves/grumpkin/grumpkin.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/flavor/ultra_recursive.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/pcs/gemini/gemini.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/pcs/gemini/gemini.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/pcs/kzg/kzg.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/pcs/shplonk/shplonk.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/proof_system/ultra_verifier.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/proof_system/verifier.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/polynomials/barycentric_data.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/polynomials/barycentric_data.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/polynomials/pow.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/relations/lookup_relation.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/relations/relation_parameters.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/sumcheck/sumcheck_round.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/honk/utils/grand_product_delta.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/proof_system/flavor/flavor.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/primitives/curves/bn254.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/transcript/transcript.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/transcript/transcript.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/ultra_recursive_verifier.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/ultra_recursive_verifier.hpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/verifier.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/utility/utility.hpp
Labels: crypto

#1881 fix: Reset keccak var inputs to 0
  circuits/cpp/barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.test.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.cpp
  circuits/cpp/barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.test.cpp
Labels: crypto
