Repository AztecProtocol/aztec-packages, pull requests merged in 2023-12, with the labels that each got.

#3479 chore: Refactor `WitnessEntities` to be able to derive `WitnessCommitments` from it
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/goblin_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/verifier.test.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.hpp
Labels: crypto

#3346 feat: new Poseidon2 circuit builder gates
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/proof_system/arithmetization/arithmetization.hpp
  barretenberg/cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.test.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/ultra_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_external_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_internal_relation.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.cpp
Labels: crypto

#3621 docs(yellowpaper): update `cast` instruction description with truncation operation
  yellow-paper/docs/public-vm/gen/_InstructionSet.mdx
  yellow-paper/src/preprocess/InstructionSet/InstructionSet.js
Labels: documentation, avm

#3419 feat: complete folding prover and verifier for ultra instances
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra.hpp
  barretenberg/cpp/src/barretenberg/honk/utils/testing.hpp
  barretenberg/cpp/src/barretenberg/honk/utils/testing.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/combiner.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/combiner_example_gen.py
  barretenberg/cpp/src/barretenberg/protogalaxy/folding_result.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/instances.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/verifier_instance.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/protogalaxy.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.hpp
Labels: crypto

#3692 docs(yellowpaper): AVM intro sections
  yellow-paper/docs/public-vm/avm.md
Labels: documentation, avm

#3709 docs(yellowpaper): finish AVM Context definitions
  yellow-paper/docs/public-vm/avm.md
Labels: documentation, avm

#3717 docs(yellowpaper): AVM high-level execution
  yellow-paper/docs/public-vm/avm.md
Labels: documentation, avm

#3749 docs(yellowpaper): avm nested call returns, updating calling context
  yellow-paper/docs/public-vm/avm.md
Labels: documentation, avm

#3732 chore(docs): Update trees page
  docs/docs/concepts/advanced/data_structures/trees.md
Labels: documentation
