Repository AztecProtocol/aztec-packages, pull requests merged in 2023-11, with the labels that each got.

#3213 docs: move Updating.md file, add aztec tag to nargo update instruction
  docs/docs/dev_docs/updating.md
  docs/netlify.toml
  docs/sidebars.js
Labels: documentation

#3215 fix: temporary fix for bb prove w/ ram rom blocks
  barretenberg/acir_tests/Dockerfile.bb
  barretenberg/cpp/src/barretenberg/bb/main.cpp
Labels: bug

#3245 feat: protogalaxy combiner quotient
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/honk/proof_system/barycentric.py
  barretenberg/cpp/src/barretenberg/polynomials/barycentric.hpp
  barretenberg/cpp/src/barretenberg/polynomials/univariate.hpp
  barretenberg/cpp/src/barretenberg/polynomials/univariate.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/combiner.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/combiner_example_gen.py
  barretenberg/cpp/src/barretenberg/protogalaxy/folding_result.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.hpp
  barretenberg/cpp/src/barretenberg/relations/nested_containers.hpp
  barretenberg/cpp/src/barretenberg/relations/utils.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/verifier_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.test.cpp
  barretenberg/cpp/src/barretenberg/transcript/transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/protogalaxy.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.hpp
Labels: crypto

#3267 chore(docs): Suggest CLI install per project
  docs/docs/dev_docs/cli/cli-commands.md
  docs/docs/dev_docs/getting_started/quickstart.md
  docs/docs/dev_docs/updating.md
Labels: documentation

#3291 feat: fold batching challenge (alpha)
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra.hpp
  barretenberg/cpp/src/barretenberg/polynomials/univariate.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/combiner.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/relations/utils.hpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/instances.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/verifier_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/protogalaxy.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
Labels: crypto

#3118 feat: added poseidon2 hash function to barretenberg/crypto
  barretenberg/cpp/src/barretenberg/crypto/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2.bench.cpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2.hpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_cpp_params.sage
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_params.hpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_permutation.hpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_permutation.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/poseidon2/sponge/sponge.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ecdsa_secp256r1.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_declarations.hpp
  barretenberg/cpp/src/barretenberg/numeric/uint256/uint256.hpp
  barretenberg/cpp/src/barretenberg/numeric/uint256/uint256.test.cpp
Labels: crypto

#3439 feat(AVM): First version for mini AVM (ADD, RETURN, CALLDATACOPY)
  barretenberg/cpp/pil/avm/avm_mini.pil
  barretenberg/cpp/pil/avm/avm_mini_opt.pil
  barretenberg/cpp/pil/fib/fibonacci.pil
  barretenberg/cpp/pil/fib/fibonacci_opt.pil
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/flavor/generated/AvmMini_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/generated/Fib_flavor.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/AvmMini_helper.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/AvmMini_helper.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/AvmMini_trace.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/AvmMini_trace.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/generated/AvmMini_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/generated/Fib_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/generated/Fib_trace.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/generated/Fib_trace.hpp
  barretenberg/cpp/src/barretenberg/relations/generated/AvmMini.hpp
  barretenberg/cpp/src/barretenberg/relations/generated/Fib.hpp
  barretenberg/cpp/src/barretenberg/vm/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_composer.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_composer.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_composer.test.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_prover.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_prover.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/AvmMini_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_composer.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_composer.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_composer.test.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_prover.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_prover.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/Fib_verifier.hpp
Labels: avm
