Repository AztecProtocol/aztec-packages, pull requests merged in 2024-04, with the labels that each got.

#5517 feat: Optimize auxiliary relations slightly
  barretenberg/cpp/src/barretenberg/relations/auxiliary_relation.hpp
Labels: optimisation, crypto

#5552 feat: Optimise relations
  barretenberg/cpp/src/barretenberg/relations/auxiliary_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_op_queue_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/elliptic_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_external_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_internal_relation.hpp
Labels: optimisation, crypto, barretenberg

#5903 chore: simplify computation of pow for each sumcheck round
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
Labels: crypto

#6063 chore: refactor recursive verifier tests
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/goblin_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/verifier.test.cpp
Labels: crypto

#1195 feat: circuit simulator for Ultra and GoblinUltra verifiers
  barretenberg/cpp/src/barretenberg/benchmark/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/simulator_bench/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/simulator_bench/simulator.bench.cpp
  barretenberg/cpp/src/barretenberg/circuit_checker/circuit_checker.hpp
  barretenberg/cpp/src/barretenberg/crypto/ecdsa/ecdsa.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/types/merkle_hash_type.hpp
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/types/pedersen_commitment_type.hpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/plonk_recursion/transcript/transcript.hpp
  barretenberg/cpp/src/barretenberg/stdlib/plonk_recursion/verification_key/verification_key.hpp
  barretenberg/cpp/src/barretenberg/stdlib/plonk_recursion/verifier/verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/address/address.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_nafs.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bit_array/bit_array.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bit_array/bit_array.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bool/bool.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bool/bool.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/byte_array/byte_array.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/byte_array/byte_array.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/circuit_builders/circuit_builders.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/circuit_builders/circuit_builders_fwd.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/array.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/array.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/logic/logic.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/logic/logic.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/packed_byte_array/packed_byte_array.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/packed_byte_array/packed_byte_array.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/plookup/plookup.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/plookup/plookup.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/safe_uint/safe_uint.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/safe_uint/safe_uint.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/safe_uint/safe_uint.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/arithmetic.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/plookup/arithmetic.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/plookup/comparison.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/plookup/logic.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/plookup/uint.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/uint.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/uint.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/uint.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/witness/witness.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_simulator.hpp
Labels: crypto
