Repository AztecProtocol/aztec-packages, pull requests merged in 2024-06, with the labels that each got.

#6849 feat: SMT Verification Module Update
  barretenberg/cpp/src/barretenberg/relations/ultra_arithmetic_relation.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.test.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bvterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/standard_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/standard_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.hpp
Labels: crypto, product-security

#6899 feat: Add standard form function to biggroup
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp
Labels: crypto

#6923 fix: Fix for the flaky issue (I hope)
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_edgecase_handling.hpp
Labels: bug

#6931 chore: fix issue #6929 (off-by-one error in `UltraCircuitBuilder::create_range_constraint`)
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.hpp
Labels: bug

#6904 feat: SMT Standard Circuit separation
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.test.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
Labels: crypto, product-security

#7067 feat: SMT Verifier for Ultra Arithmetization
  barretenberg/cpp/src/barretenberg/smt_verification/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_polynomials.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/standard_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
Labels: crypto, product-security

#7094 chore: Remove unneeded public input folding
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover_impl.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
Labels: crypto

#7078 chore: take the PCS out of Zeromorph and refactor tests
  barretenberg/cpp/src/barretenberg/benchmark/ultra_bench/ultra_honk_rounds.bench.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplonk.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/verification_key.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/verifier_commitment_key.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/verifier_commitment_key.test.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/crs_factory.hpp
  barretenberg/cpp/src/barretenberg/srs/factories/file_crs_factory.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/file_crs_factory.hpp
  barretenberg/cpp/src/barretenberg/srs/factories/mem_bn254_crs_factory.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/mem_crs_factory.test.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/mem_grumpkin_crs_factory.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_prover.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_prover.hpp
  yarn-project/end-to-end/src/e2e_prover/file
  yarn-project/end-to-end/src/e2e_prover/full_test
  yarn-project/end-to-end/src/e2e_prover/output
Labels: crypto

#7164 feat: Shplonk revival in ECCVM
  barretenberg/cpp/src/barretenberg/benchmark/ipa_bench/ipa.bench.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplonk.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplonk.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_prover.cpp
Labels: crypto

#7182 feat: Enable merge recursive verifier in Goblin recursive verifier
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/client_ivc_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/client_ivc_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/goblin_recursive_verifier.cpp
Labels: crypto
