Repository AztecProtocol/aztec-packages, pull requests merged in 2024-08, with the labels that each got.

#7709 feat: consistent handling of point at infinity in transcript
  barretenberg/cpp/src/barretenberg/ecc/fields/field_conversion.hpp
  barretenberg/cpp/src/barretenberg/ecc/groups/affine_element.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/groups/affine_element_impl.hpp
  barretenberg/cpp/src/barretenberg/ecc/groups/element_impl.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/transcript/transcript.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field_conversion.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
Labels: crypto

#8051 feat: passes copy_cycles by const reference to avoid copying
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/composer/permutation_lib.hpp
Labels: barretenberg

#8119 docs: Update installation info for bb and noir
  barretenberg/cpp/src/barretenberg/bb/readme.md
Labels: documentation

#8118 feat: Free instances and circuits earlier to reduce max memory usage
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_kernel_pinning.test.cpp
  barretenberg/cpp/src/barretenberg/execution_trace/execution_trace.cpp
  barretenberg/cpp/src/barretenberg/execution_trace/execution_trace.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/composer/permutation_lib.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover_impl.hpp
  barretenberg/cpp/src/barretenberg/srs/factories/file_crs_factory.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/file_crs_factory.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp
Labels: crypto

#8273 docs: Minor fixes
  docs/docs/aztec/concepts/accounts/keys.md
  docs/docs/reference/developer_references/smart_contract_reference/storage/private_state.md
  docs/docusaurus.config.js
Labels: documentation
