Repository AztecProtocol/aztec-packages, pull requests merged in 2024-07, with the labels that each got.

#6768 feat: added barrett_reduction implementation into uintx
  barretenberg/cpp/src/barretenberg/benchmark/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/circuit_construction_bench/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/circuit_construction_bench/circuit_construction.bench.cpp
  barretenberg/cpp/src/barretenberg/numeric/uintx/uintx.hpp
  barretenberg/cpp/src/barretenberg/numeric/uintx/uintx.test.cpp
  barretenberg/cpp/src/barretenberg/numeric/uintx/uintx_impl.hpp
Labels: optimisation

#7440 fix: lagrange interpolation
  barretenberg/cpp/src/barretenberg/polynomials/polynomial_arithmetic.cpp
  barretenberg/cpp/src/barretenberg/polynomials/polynomial_arithmetic.test.cpp
Labels: crypto

#7601 chore(bb readme): Add installation instructions and TODOs
  barretenberg/cpp/src/barretenberg/bb/readme.md
Labels: documentation, barretenberg, bb bin

#7608 chore(bb readme): Update versioning instructions and add Honk Solidity verifier commands
  barretenberg/cpp/src/barretenberg/bb/readme.md
Labels: documentation, barretenberg, bb bin

#7126 feat: extend SMT Utils
  barretenberg/cpp/src/barretenberg/smt_verification/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/README.md
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.hpp
Labels: crypto, product-security
