Repository AztecProtocol/aztec-packages, pull requests merged in 2024-05, with the labels that each got.

#6150 feat: Recursive folding verifier and decider as ultra circuits and circuit simulator
  barretenberg/cpp/src/barretenberg/circuit_checker/circuit_checker.hpp
  barretenberg/cpp/src/barretenberg/circuit_checker/ultra_circuit_checker.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_kernel_pinning.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/poseidon2/poseidon2_permutation.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/poseidon2/poseidon2_permutation.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/protogalaxy_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/protogalaxy_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_bn254.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/circuit_builders/circuit_builders.hpp
Labels: crypto

#6354 feat: Small translator optimisations
  barretenberg/cpp/src/barretenberg/honk/proof_system/permutation_library.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_decomposition_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_non_native_field_relation.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_prover.cpp
Labels: optimisation, crypto

#5841 docs: sumcheck documentation
  barretenberg/cpp/docs/src/sumcheck-outline.md
  barretenberg/cpp/src/barretenberg/polynomials/pow.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_output.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
Labels: crypto

#6415 fix: increase N_max in Zeromorph
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.hpp
Labels: crypto

#6327 feat: translator recursive verifier
  barretenberg/cpp/scripts/analyze_client_ivc_bench.py
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/goblin_bench/goblin.bench.cpp
  barretenberg/cpp/src/barretenberg/benchmark/relations_bench/relations.bench.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/relation_definitions.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/goblin/translation_evaluations.hpp
  barretenberg/cpp/src/barretenberg/honk/proof_system/permutation_library.hpp
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/arithmetization/arithmetization.hpp
  barretenberg/cpp/src/barretenberg/relations/relation_parameters.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_decomposition_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_decomposition_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_decomposition_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_delta_range_constraint_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_delta_range_constraint_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_delta_range_constraint_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_non_native_field_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_non_native_field_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_non_native_field_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_permutation_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_permutation_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_permutation_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_relation_consistency.test.cpp
  barretenberg/cpp/src/barretenberg/relations/utils.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field_conversion.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/goblin_ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_composer.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_mini.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_verifier.hpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_decomposition_relation.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_delta_range_constraint_relation.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_extra_relations.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_non_native_field_relation.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_permutation_relation.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.test.cpp
Labels: crypto

#6565 chore: parameterise cycle_group by `Builder` rather than `Composer`
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.hpp
Labels: crypto

#6027 feat: Changing finite field arithmetic in wasm to 29 bits for multiplications (second try, disabled AVM build in wasm)
  barretenberg/cpp/scripts/benchmark_wasm_remote_wasmer.sh
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/benchmark/basics_bench/basics.bench.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq12.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq12.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq2.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq2.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq6.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq6.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fr.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fr.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/g1.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/g2.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/grumpkin/grumpkin.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256k1/secp256k1.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256k1/secp256k1.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256r1/secp256r1.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256r1/secp256r1.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_declarations.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_docs.md
  barretenberg/cpp/src/barretenberg/ecc/fields/field_impl.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_impl_generic.hpp
  barretenberg/cpp/src/barretenberg/numeric/uint256/uint256.hpp
  barretenberg/cpp/src/barretenberg/numeric/uint256/uint256_impl.hpp
  barretenberg/cpp/src/barretenberg/polynomials/univariate.hpp
  barretenberg/cpp/src/barretenberg/relations/auxiliary_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/delta_range_constraint_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_op_queue_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_msm_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_point_table_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_transcript_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_wnaf_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/elliptic_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_external_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/poseidon2_internal_relation.hpp
  barretenberg/cpp/src/barretenberg/vm/CMakeLists.txt
Labels: optimisation, crypto

#6647 feat: Instantiate ECCVM relations on bigfield
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_lookup_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_msm_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_point_table_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_relation_consistency.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_set_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_transcript_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_wnaf_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/relation_definitions.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_lookup_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_lookup_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_msm_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_msm_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_point_table_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_point_table_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_set_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_set_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_transcript_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_transcript_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_wnaf_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_wnaf_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.test.cpp
Labels: crypto

#6413 feat: sumcheck part of ECCVM recursive verifier instantiated as an UltraCircuit
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_bools_relation.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/ecc_relation_consistency.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/eccvm_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/verifier_commitment_key.hpp
  barretenberg/cpp/src/barretenberg/eccvm_recursion/verifier_commitment_key.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_bools_relation.cpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_bools_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_transcript_relation_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/curves/grumpkin.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/spike_flavor.hpp
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/index.ts
Labels: crypto

#6743 fix: CCI jobs for avm-transpiler and aztec-nargo should require job noir as prereq
  .circleci/config.yml
Labels: devops

#6725 feat: pow method for bigfield
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.hpp
Labels: crypto

#6744 feat: cycle scalar <> bigfield interactions
  barretenberg/barretenberg.code-workspace
  barretenberg/cpp/src/barretenberg/dsl/acir_format/multi_scalar_mul.cpp
  barretenberg/cpp/src/barretenberg/stdlib/commitment/pedersen/pedersen.cpp
  barretenberg/cpp/src/barretenberg/stdlib/encryption/schnorr/schnorr.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/pedersen/pedersen.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.test.cpp
Labels: crypto

#6778 feat: Goblin Recursive Verifier
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/goblin_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/goblin_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/goblin_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/merge_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/translator_vm_recursion/translator_recursive_verifier.test.cpp
Labels: crypto
