Repository AztecProtocol/aztec-packages, pull requests merged in 2024-03, with the labels that each got.

#4908 fix: Remove the `VerificationKey` from `ProverInstance`
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/goblin_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/merge_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/protogalaxy_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/verifier.test.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/databus_composer.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_composer.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_composer.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
Labels: crypto

#4852 feat(avm-simulator): implement AVM message opcodes (simulator/transpiler/noir-test)
  avm-transpiler/src/opcodes.rs
  avm-transpiler/src/transpile.rs
  barretenberg/cpp/src/barretenberg/vm/avm_trace/avm_opcode.cpp
  barretenberg/cpp/src/barretenberg/vm/avm_trace/avm_opcode.hpp
  noir-projects/aztec-nr/aztec/src/context/avm.nr
  noir-projects/noir-contracts/contracts/avm_test_contract/src/main.nr
  yarn-project/simulator/src/avm/avm_simulator.test.ts
  yarn-project/simulator/src/avm/fixtures/index.ts
  yarn-project/simulator/src/avm/journal/journal.test.ts
  yarn-project/simulator/src/avm/journal/journal.ts
  yarn-project/simulator/src/avm/journal/trace.test.ts
  yarn-project/simulator/src/avm/journal/trace.ts
  yarn-project/simulator/src/avm/journal/trace_types.ts
  yarn-project/simulator/src/avm/opcodes/accrued_substate.test.ts
  yarn-project/simulator/src/avm/opcodes/accrued_substate.ts
  yarn-project/simulator/src/avm/serialization/bytecode_serialization.ts
  yarn-project/simulator/src/avm/serialization/instruction_serialization.ts
  yellow-paper/docs/public-vm/execution.md
  yellow-paper/docs/public-vm/gen/_instruction-set.mdx
  yellow-paper/docs/public-vm/state.md
  yellow-paper/docs/public-vm/type-structs.md
  yellow-paper/src/preprocess/InstructionSet/InstructionSet.js
Labels: avm

#4862 chore(avm-transpiler): prefix AVM opcode oracles with avmOpcode
  avm-transpiler/src/transpile.rs
  noir-projects/aztec-nr/aztec/src/avm/hash.nr
  noir-projects/aztec-nr/aztec/src/context/avm.nr
Labels: avm

#4863 chore(avm-simulator): test cleanup using `expect.objectContaining()`
  yarn-project/simulator/src/avm/journal/journal.test.ts
  yarn-project/simulator/src/avm/journal/trace.test.ts
  yarn-project/simulator/src/avm/opcodes/accrued_substate.test.ts
Labels: avm

#4884 feat: Adding fr compatibility to smt variables api
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/README.md
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.test.cpp
Labels: crypto, product-security

#5084 refactor: remove eccvm functionality to update the op queue and ensure ultra ops are populated through function
  barretenberg/cpp/src/barretenberg/benchmark/goblin_bench/eccvm.bench.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/eccvm/eccvm_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/eccvm/eccvm_circuit_builder.test.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/proof_system/op_queue/ecc_op_queue.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_composer.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/merge_prover.cpp
Labels: crypto

#5096 feat: Update the core of SMT Circuit class
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/standard_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/standard_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_bigfield.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
Labels: crypto, product-security

#4854 refactor: interaction for a mock first circuit handled inside the `EccOpQueue`
  barretenberg/cpp/src/barretenberg/bb/main.cpp
  barretenberg/cpp/src/barretenberg/benchmark/goblin_bench/goblin.bench.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin_recursion.test.cpp
  barretenberg/cpp/src/barretenberg/goblin/mock_circuits.hpp
  barretenberg/cpp/src/barretenberg/goblin/mock_circuits_pinning.test.cpp
  barretenberg/cpp/src/barretenberg/proof_system/op_queue/ecc_op_queue.hpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/goblin_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/recursion/honk/verifier/merge_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/databus_composer.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_composer.test.cpp
Labels: crypto

#5176 feat: Update SMT Circuit class and add gate relaxation functionality
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.hpp
Labels: crypto, product-security

#5210 chore: Oink
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_prover.hpp
Labels: 🔥 high priority

#5215 refactor: template Zeromorph by PCS
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/decider_prover.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/merge_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_prover.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_prover.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/goblin_ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_prover.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/avm_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/generated/toy_prover.hpp
  barretenberg/cpp/src/barretenberg/vm/generated/toy_verifier.cpp
Labels: crypto

#5140 feat: Extended IPA tests and fuzzing
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/mock_transcript.hpp
  barretenberg/cpp/src/barretenberg/common/mem.hpp
  barretenberg/cpp/src/barretenberg/ecc/groups/affine_element.hpp
  barretenberg/cpp/src/barretenberg/ecc/groups/affine_element.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/groups/element.hpp
  barretenberg/cpp/src/barretenberg/ecc/groups/element_impl.hpp
Labels: crypto

#4508 feat!: automatic NoteInterface and NoteGetterOptions auto select
  avm-transpiler/Cargo.lock
  docs/docs/developers/contracts/references/storage/private_state.md
  docs/docs/misc/migration_notes.md
  noir-projects/aztec-nr/address-note/src/address_note.nr
  noir-projects/aztec-nr/aztec/src/note/note_getter.nr
  noir-projects/aztec-nr/aztec/src/note/note_getter_options.nr
  noir-projects/aztec-nr/aztec/src/note/note_interface.nr
  noir-projects/aztec-nr/aztec/src/note/note_viewer_options.nr
  noir-projects/aztec-nr/aztec/src/oracle/notes.nr
  noir-projects/aztec-nr/field-note/src/field_note.nr
  noir-projects/aztec-nr/value-note/src/utils.nr
  noir-projects/aztec-nr/value-note/src/value_note.nr
  noir-projects/noir-contracts/contracts/app_subscription_contract/src/subscription_note.nr
  noir-projects/noir-contracts/contracts/benchmarking_contract/src/main.nr
  noir-projects/noir-contracts/contracts/card_game_contract/src/cards.nr
  noir-projects/noir-contracts/contracts/child_contract/src/main.nr
  noir-projects/noir-contracts/contracts/delegated_on_contract/src/main.nr
  noir-projects/noir-contracts/contracts/delegator_contract/src/main.nr
  noir-projects/noir-contracts/contracts/docs_example_contract/src/main.nr
  noir-projects/noir-contracts/contracts/docs_example_contract/src/options.nr
  noir-projects/noir-contracts/contracts/docs_example_contract/src/types/card_note.nr
  noir-projects/noir-contracts/contracts/ecdsa_account_contract/src/ecdsa_public_key_note.nr
  noir-projects/noir-contracts/contracts/escrow_contract/src/main.nr
  noir-projects/noir-contracts/contracts/inclusion_proofs_contract/src/main.nr
  noir-projects/noir-contracts/contracts/schnorr_account_contract/src/public_key_note.nr
  noir-projects/noir-contracts/contracts/test_contract/src/main.nr
  noir-projects/noir-contracts/contracts/token_blacklist_contract/src/main.nr
  noir-projects/noir-contracts/contracts/token_blacklist_contract/src/types/token_note.nr
  noir-projects/noir-contracts/contracts/token_blacklist_contract/src/types/transparent_note.nr
  noir-projects/noir-contracts/contracts/token_contract/src/main.nr
  noir-projects/noir-contracts/contracts/token_contract/src/types/token_note.nr
  noir-projects/noir-contracts/contracts/token_contract/src/types/transparent_note.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/function_selector.nr
  noir-projects/noir-protocol-circuits/crates/types/src/contract_class_id.nr
  noir-projects/noir-protocol-circuits/crates/types/src/traits.nr
  noir/noir-repo/Cargo.lock
  noir/noir-repo/aztec_macros/Cargo.toml
  noir/noir-repo/aztec_macros/src/lib.rs
  noir/noir-repo/aztec_macros/src/transforms/mod.rs
  noir/noir-repo/aztec_macros/src/transforms/note_interface.rs
  noir/noir-repo/aztec_macros/src/utils/ast_utils.rs
  noir/noir-repo/aztec_macros/src/utils/errors.rs
  noir/noir-repo/compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
  noir/noir-repo/compiler/noirc_frontend/src/hir/def_map/mod.rs
  noir/noir-repo/compiler/noirc_frontend/src/lib.rs
  yarn-project/simulator/src/acvm/oracle/oracle.ts
  yarn-project/simulator/src/acvm/oracle/typed_oracle.ts
  yarn-project/simulator/src/client/client_execution_context.ts
  yarn-project/simulator/src/client/pick_notes.test.ts
  yarn-project/simulator/src/client/pick_notes.ts
  yarn-project/simulator/src/client/view_data_oracle.ts
Labels: aztec.nr

#5254 feat: Merge SMT Terms in one class
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_bigfield.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_polynomials.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bool.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bvterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.hpp
Labels: crypto, product-security

#5315 refactor: moving public inputs back to instance
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/recursive_verifier_instance.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/verifier_instance.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_verifier.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
Labels: crypto

#5246 feat: ZeroMorph working with IPA and integration with ECCVM
  barretenberg/cpp/src/barretenberg/benchmark/ipa_bench/ipa.bench.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/zeromorph/zeromorph.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/flavor/ecc_vm.hpp
  barretenberg/cpp/src/barretenberg/flavor/goblin_ultra.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_recursion/verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/goblin_translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/merge_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
Labels: crypto

#5409 feat: read_calldata
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/proof_system/circuit_builder/goblin_ultra_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/instance/prover_instance.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/databus_composer.test.cpp
Labels: crypto

#5413 chore: Remove mocking function in `EccOpQueue` again
  barretenberg/cpp/src/barretenberg/proof_system/op_queue/ecc_op_queue.hpp
Labels: crypto

#5376 fix(avm-simulator): hashing opcodes indirection
  avm-transpiler/src/transpile.rs
  yarn-project/simulator/src/avm/avm_memory_types.test.ts
  yarn-project/simulator/src/avm/avm_memory_types.ts
  yarn-project/simulator/src/avm/opcodes/comparators.test.ts
  yarn-project/simulator/src/avm/opcodes/hashing.test.ts
  yarn-project/simulator/src/avm/opcodes/hashing.ts
Labels: avm

#5396 feat(avm): add AvmContextInputs
  noir-projects/aztec-nr/aztec/src/context/avm_context.nr
  noir-projects/aztec-nr/aztec/src/context/inputs.nr
  noir-projects/aztec-nr/aztec/src/context/inputs/avm_context_inputs.nr
  noir-projects/noir-contracts/contracts/avm_test_contract/src/main.nr
  noir/noir-repo/aztec_macros/src/transforms/functions.rs
  yarn-project/simulator/src/avm/avm_context.test.ts
  yarn-project/simulator/src/avm/avm_execution_environment.test.ts
  yarn-project/simulator/src/avm/avm_execution_environment.ts
  yarn-project/simulator/src/avm/avm_simulator.test.ts
  yarn-project/simulator/src/avm/fixtures/index.ts
  yarn-project/simulator/src/avm/opcodes/external_calls.test.ts
  yarn-project/simulator/src/avm/opcodes/memory.test.ts
Labels: avm

#5436 feat: fold proving key polys instead of prover polys
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.cpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/goblin_ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_flavor.hpp
Labels: crypto

#5468 chore: add goblin ops in add_gates_to_ensure_all_polys_are_non_zero
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/goblin_acir_composer.cpp
  barretenberg/cpp/src/barretenberg/goblin/goblin_recursion.test.cpp
  barretenberg/cpp/src/barretenberg/goblin/mock_circuits.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/goblin_ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mock_circuits.hpp
Labels: crypto
