Repository AztecProtocol/aztec-packages, pull requests merged in 2025-03, with the labels that each got.

#12358 feat: prod network deployments
  spartan/aztec-network/files/config/config-full-node-env.sh
  spartan/aztec-network/files/config/config-prover-env.sh
  spartan/aztec-network/files/config/setup-service-addresses.sh
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/eth/eth-entrypoint-configmap.yaml
  spartan/aztec-network/templates/full-node.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/templates/validator.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/slim.yaml
  spartan/bootstrap.sh
  spartan/scripts/deploy_kind.sh
  spartan/scripts/test_prod_deployment.sh
Labels: ci-full

#12387 chore: Add logging to isolated prover client tests and bump CPUs
  yarn-project/bootstrap.sh
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/scripts/run_test.sh
Labels: ci-full

#12393 refactor: Simplify port forwarding and process management in kind tests
  spartan/scripts/test_kind.sh
  yarn-project/end-to-end/src/spartan/4epochs.test.ts
  yarn-project/end-to-end/src/spartan/gating-passive.test.ts
  yarn-project/end-to-end/src/spartan/prover-node.test.ts
  yarn-project/end-to-end/src/spartan/proving.test.ts
  yarn-project/end-to-end/src/spartan/reorg.test.ts
  yarn-project/end-to-end/src/spartan/smoke.test.ts
  yarn-project/end-to-end/src/spartan/transfer.test.ts
  yarn-project/end-to-end/src/spartan/upgrade_governance_proposer.test.ts
  yarn-project/end-to-end/src/spartan/upgrade_rollup_version.test.ts
  yarn-project/end-to-end/src/spartan/utils.ts
Labels: ci-full

#12283 feat(p2p): test scenario - validators have non persistent ENRs
  yarn-project/bootstrap.sh
  yarn-project/p2p/bootstrap.sh
  yarn-project/p2p/src/testbench/port_change.test.ts
  yarn-project/p2p/src/testbench/testbench.ts
  yarn-project/p2p/src/testbench/worker_client_manager.ts
  yarn-project/p2p/testbench/configurations/normal-degree-20-nodes.json
  yarn-project/scripts/run_test.sh
Labels: ci-external

#12343 feat: Combine group polynomials in translator by interleaving rather than concatenation
  barretenberg/cpp/src/barretenberg/commitment_schemes/claim_batcher.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini_impl.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplemini.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/utils/mock_witness_generator.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/utils/test_utils.hpp
  barretenberg/cpp/src/barretenberg/polynomials/polynomial.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_verifier.cpp
Labels: crypto

#12489 feat: Enrich env vars based on network option
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/aztec/src/cli/chain_l2_config.ts
Labels: ci-full

#12555 fix: bbup
  barretenberg/bbup/bbup
  barretenberg/bbup/bootstrap.sh
Labels: arm64-ci, ci-full

#12470 fix: update fallback transport
  playground/vite.config.ts
  yarn-project/archiver/package.json
  yarn-project/aztec-faucet/package.json
  yarn-project/aztec.js/package.json
  yarn-project/aztec/package.json
  yarn-project/bb-prover/package.json
  yarn-project/blob-sink/package.json
  yarn-project/cli/package.json
  yarn-project/end-to-end/package.json
  yarn-project/end-to-end/src/spartan/4epochs.test.ts
  yarn-project/end-to-end/src/spartan/setup_test_wallets.ts
  yarn-project/end-to-end/src/spartan/transfer.test.ts
  yarn-project/epoch-cache/package.json
  yarn-project/ethereum/package.json
  yarn-project/ethereum/src/l1_tx_utils.test.ts
  yarn-project/ethereum/src/test/fallback_transport.test.ts
  yarn-project/foundation/package.json
  yarn-project/p2p/package.json
  yarn-project/prover-node/package.json
  yarn-project/pxe/package.json
  yarn-project/sequencer-client/package.json
  yarn-project/simulator/package.json
  yarn-project/stdlib/package.json
  yarn-project/validator-client/package.json
  yarn-project/yarn.lock
Labels: ci-full

#12610 chore: Fix mac build
  barretenberg/cpp/src/barretenberg/vm2/tracegen/lib/lookup_into_p_decomposition.hpp
Labels: ci-full

#12611 fix: broken kind transfer test
  .test_patterns.yml
  spartan/aztec-network/templates/blob-sink.yaml
Labels: ci-full

#12558 chore: clean up upgrade test and other small things
  spartan/aztec-network/values/ci.yaml
  yarn-project/cli/src/utils/aztec.ts
  yarn-project/end-to-end/src/spartan/upgrade_rollup_version.test.ts
  yarn-project/ethereum/src/contracts/governance.test.ts
  yarn-project/ethereum/src/contracts/governance.ts
  yarn-project/ethereum/src/contracts/governance_proposer.ts
  yarn-project/ethereum/src/contracts/registry.test.ts
  yarn-project/ethereum/src/contracts/registry.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
  yarn-project/ethereum/src/queries.ts
Labels: ci-full

#12637 feat!: disable PXE concurrency
  docs/docs/migration_notes.md
  yarn-project/pxe/src/pxe_service/pxe_service.ts
Labels: ci-full

#12685 fix: slashing test
  yarn-project/end-to-end/src/e2e_p2p/slashing.test.ts
Labels: ci-full

#12114 feat(spartan): add seperate resources files
  .github/workflows/network-deploy.yml
  spartan/aztec-network/resources/default.yaml
  spartan/aztec-network/resources/gcloud.yaml
  spartan/aztec-network/resources/mainframe.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/1-validators.yaml
  spartan/aztec-network/values/16-validators-with-metrics.yaml
  spartan/aztec-network/values/3-validators-with-metrics.yaml
  spartan/aztec-network/values/ci-sepolia.yaml
  spartan/aztec-network/values/ci-smoke.yaml
  spartan/aztec-network/values/ci.yaml
  spartan/aztec-network/values/exp-1.yaml
  spartan/aztec-network/values/exp-2.yaml
  spartan/aztec-network/values/ignition-reth.yaml
  spartan/aztec-network/values/sepolia-48-validators-with-proving-and-metrics.yaml
  spartan/aztec-network/values/slim.yaml
  spartan/scripts/deploy_kind.sh
  spartan/scripts/test_kind.sh
  spartan/terraform/deploy-metrics/main.tf
  spartan/terraform/deploy-release/main.tf
  spartan/terraform/deploy-release/variables.tf
  yarn-project/end-to-end/src/spartan/utils.ts
Labels: ci-full

#12385 fix: Patches to cycle_group and cycle_group fuzzer
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/common/fuzzer.hpp
  barretenberg/cpp/src/barretenberg/examples/join_split/join_split_circuit.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bool/bool.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
Labels: T-bug

#12535 fix: redo "fix: make vk metadata actual witnesses"
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/oink_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_key.hpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_keys.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_rollup_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm/avm/generated/flavor.cpp
  barretenberg/cpp/src/barretenberg/vm/avm/generated/flavor.hpp
  barretenberg/cpp/src/barretenberg/vm/avm/generated/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm/avm/recursion/recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm/avm/tests/recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/generated/flavor.cpp
  barretenberg/cpp/src/barretenberg/vm2/generated/flavor.hpp
  bb-pilcom/bb-pil-backend/templates/flavor.cpp.hbs
  bb-pilcom/bb-pil-backend/templates/flavor.hpp.hbs
Labels: ci-full

#12807 chore: simplify note getter oracle
  noir-projects/aztec-nr/aztec/src/note/note_getter.nr
  noir-projects/aztec-nr/aztec/src/oracle/notes.nr
Labels: ci-full

#12812 fix: Some basic re-org handling
  yarn-project/archiver/src/archiver/archiver.test.ts
  yarn-project/archiver/src/archiver/archiver.ts
Labels: ci-full

#12823 chore: begin the introduction of log type id and standard log layouts
  noir-projects/aztec-nr/aztec/src/discovery/mod.nr
  noir-projects/aztec-nr/aztec/src/discovery/nonce_discovery.nr
  noir-projects/aztec-nr/aztec/src/discovery/partial_notes.nr
  noir-projects/aztec-nr/aztec/src/discovery/private_logs.nr
  noir-projects/aztec-nr/aztec/src/discovery/private_notes.nr
  noir-projects/aztec-nr/aztec/src/encrypted_logs/log_assembly_strategies/default_aes128/note/note.nr
  noir-projects/aztec-nr/aztec/src/macros/aztec.nr
  noir-projects/aztec-nr/aztec/src/oracle/message_discovery.nr
Labels: ci-full

#12835 fix: agent reporting jobs completion correctly
  yarn-project/prover-client/src/proving_broker/proving_agent.test.ts
  yarn-project/prover-client/src/proving_broker/proving_agent.ts
  yarn-project/prover-client/src/proving_broker/proving_broker_agent_integration.test.ts
  yarn-project/prover-client/src/proving_broker/proving_job_controller.test.ts
  yarn-project/prover-client/src/proving_broker/proving_job_controller.ts
Labels: ci-full

#12126 feat: precomputed ClientIVC VKs
  .github/workflows/ci3.yml
  aztec-nargo/compile_then_postprocess.sh
  barretenberg/README.md
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/flows/prove_and_verify.sh
  barretenberg/acir_tests/flows/prove_then_verify_client_ivc.sh
  barretenberg/acir_tests/flows/prove_then_verify_tube.sh
  barretenberg/acir_tests/scripts/run_test.sh
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/scripts/ci_benchmark_ivc_flows.sh
  barretenberg/cpp/scripts/generate_civc_vks.sh
  barretenberg/cpp/src/barretenberg/api/api.hpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.hpp
  barretenberg/cpp/src/barretenberg/bb/main.cpp
  barretenberg/cpp/src/barretenberg/bb/readme.md
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc_integration.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_circuit_producer.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/test_bench_shared.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/sol/test/honk/TestBaseHonkZK.sol
  ci3/cache_content_hash
  ci3/github_master_failure_summary
  noir-projects/noir-contracts/bootstrap.sh
  noir-projects/noir-protocol-circuits/bootstrap.sh
  release-image/Dockerfile.dockerignore
  yarn-project/archiver/src/archiver/data_retrieval.ts
  yarn-project/bb-prover/.gitignore
  yarn-project/bb-prover/package.json
  yarn-project/bb-prover/scripts/generate_civc_vks.sh
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/prover/bb_prover.ts
  yarn-project/bb-prover/src/prover/client_ivc_proof_utils.ts
  yarn-project/bb-prover/src/verifier/bb_verifier.ts
  yarn-project/bb-prover/src/wasm/bb_wasm_private_kernel_prover.ts
  yarn-project/bootstrap.sh
  yarn-project/end-to-end/.gitignore
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/src/e2e_prover/full.test.ts
  yarn-project/ivc-integration/src/native_client_ivc_integration.test.ts
  yarn-project/prover-client/src/orchestrator/orchestrator.ts
  yarn-project/prover-client/src/orchestrator/orchestrator_workflow.test.ts
  yarn-project/prover-client/src/orchestrator/tx-proving-state.ts
  yarn-project/stdlib/src/proofs/client_ivc_proof.ts
  yarn-project/stdlib/src/rollup/tube_inputs.ts
Labels: ci-full

#12900 chore: Remove magic number from AVM bytecode
  avm-transpiler/src/transpile.rs
  yarn-project/simulator/src/public/avm/avm_simulator.test.ts
  yarn-project/simulator/src/public/avm/avm_simulator.ts
  yarn-project/simulator/src/public/avm/bytecode_utils.ts
  yarn-project/simulator/src/public/avm/opcodes/external_calls.test.ts
Labels: ci-full

#12603 chore(p2p): add tx queue to prevent ddos attacks
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/aztec.js/src/api/contract.ts
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/end-to-end/src/e2e_prover/full.test.ts
Labels: ci-external, ci-full

#12917 fix: avm merkle cpp broke darwin
  barretenberg/cpp/src/barretenberg/vm2/simulation/merkle_check.cpp
Labels: ci-full

#12822 feat: Montgomery optimisation (partial)
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fq.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/fr.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256k1/secp256k1.hpp
  barretenberg/cpp/src/barretenberg/ecc/curves/secp256r1/secp256r1.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_declarations.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_impl_generic.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/parameter_helper.py
Labels: T-optimisation

#12911 feat: use msgpack for ClientIvc::Proof in API
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
Labels: ci-full

#12964 chore: Set default proving config to true
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/sandbox/sandbox.ts
  yarn-project/end-to-end/src/fixtures/snapshot_manager.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/prover-client/src/proving_broker/config.ts
  yarn-project/pxe/src/config/index.ts
  yarn-project/stdlib/src/interfaces/prover-client.ts
Labels: ci-full

#12930 feat(p2p): capture all gossipsub metrics
  yarn-project/end-to-end/scripts/run_test.sh
  yarn-project/telemetry-client/src/prom_otel_adapter.test.ts
  yarn-project/telemetry-client/src/prom_otel_adapter.ts
Labels: ci-external

#11772 fix: make circuit parsing deterministic
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_to_constraint_buf.cpp
Labels: ci-external

#13043 chore: fix governance util issue
  spartan/bootstrap.sh
  yarn-project/cli/src/cmds/l1/governance_utils.ts
  yarn-project/ethereum/src/contracts/fee_juice.ts
Labels: ci-full

#12984 chore: towards no more mock op_queues
  barretenberg/cpp/src/barretenberg/goblin/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/goblin/mock_circuits.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_delta_range_constraint_relation.hpp
  barretenberg/cpp/src/barretenberg/srs/global_crs.hpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/merge_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/mega_honk.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/merge_prover.cpp
Labels: crypto

#13066 fix: Fix the TEST_ACCOUNTS env var
  yarn-project/aztec-node/src/aztec-node/config.ts
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/prover-node/src/config.ts
Labels: ci-full

#13071 fix: Upgrade scripts and cli require test accounts and sponsored fpc
  spartan/scripts/upgrade_rollup_with_lock.sh
  yarn-project/cli/src/cmds/l1/deploy_l1_contracts.ts
  yarn-project/cli/src/cmds/l1/deploy_new_rollup.ts
  yarn-project/cli/src/cmds/l1/index.ts
Labels: ci-full

#12921 fix: cycle_group fuzzer
  barretenberg/cpp/CMakeLists.txt
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.hpp
Labels: T-bug

#13088 fix: validate private double spends in txs with public funcs
  yarn-project/end-to-end/src/e2e_double_spend.test.ts
  yarn-project/end-to-end/src/e2e_private_voting_contract.test.ts
  yarn-project/p2p/src/msg_validators/tx_validator/double_spend_validator.test.ts
  yarn-project/p2p/src/msg_validators/tx_validator/double_spend_validator.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/sequencer-client/src/tx_validator/tx_validator_factory.ts
  yarn-project/simulator/src/public/public_processor/public_processor.test.ts
  yarn-project/simulator/src/public/public_processor/public_processor.ts
  yarn-project/stdlib/src/tests/mocks.ts
Labels: ci-external

#13151 feat: making SyncDataProvider throw before sync
  yarn-project/pxe/src/pxe_oracle_interface/pxe_oracle_interface.ts
  yarn-project/pxe/src/storage/sync_data_provider/sync_data_provider.ts
  yarn-project/pxe/src/synchronizer/synchronizer.ts
Labels: ci-full

#13128 chore: Merge alpha back to master
  aztec-up/bin/aztec
  spartan/aztec-network/values/alpha-testnet.yaml
  spartan/scripts/upgrade_rollup_with_lock.sh
  yarn-project/aztec-node/src/aztec-node/config.ts
  yarn-project/aztec/src/bin/index.ts
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/aztec/src/cli/chain_l2_config.ts
  yarn-project/cli/src/cmds/l1/deploy_l1_contracts.ts
  yarn-project/cli/src/cmds/l1/deploy_l1_verifier.ts
  yarn-project/cli/src/cmds/l1/deploy_new_rollup.ts
  yarn-project/cli/src/cmds/l1/index.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/prover-node/src/config.ts
Labels: ci-full

#12816 feat: split public inputs from proof
  barretenberg/acir_tests/bbjs-test/src/index.ts
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/flows/bb_prove_bbjs_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_bb_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/flows/prove_then_verify.sh
  barretenberg/acir_tests/flows/sol_honk.sh
  barretenberg/acir_tests/flows/sol_honk_zk.sh
  barretenberg/acir_tests/sol-test/src/index.js
  barretenberg/cpp/src/barretenberg/api/api.hpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.hpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/api/write_prover_output.hpp
  barretenberg/cpp/src/barretenberg/bb/main.cpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/honk/proof_system/types/proof.hpp
  barretenberg/sol/src/ultra/keys/Add2UltraVerificationKey.sol
  barretenberg/sol/src/ultra/keys/BlakeUltraVerificationKey.sol
  barretenberg/sol/src/ultra/keys/EcdsaUltraVerificationKey.sol
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/prover/bb_prover.ts
  yarn-project/prover-client/src/test/bb_prover_full_rollup.test.ts
  yarn-project/prover-node/src/prover-node-publisher.ts
  yarn-project/stdlib/src/proofs/proof.ts
Labels: ci-full
