Repository AztecProtocol/aztec-packages, pull requests merged in 2025-09, with the labels that each got.

#16201 refactor(bb): remove --output_format, have one-size-fits-all format
  barretenberg/acir_tests/bbjs-test/src/index.ts
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/browser-test-app/src/index.ts
  barretenberg/acir_tests/scripts/bb_prove_bbjs_verify.sh
  barretenberg/acir_tests/scripts/bb_prove_sol_verify.sh
  barretenberg/acir_tests/scripts/bbjs_prove_bb_verify.sh
  barretenberg/acir_tests/scripts/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/sol-test/src/index.js
  barretenberg/bootstrap.sh
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/api/api.hpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.hpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.test.cpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/bbapi/c_bind.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/private_execution_steps.cpp
  barretenberg/cpp/src/barretenberg/common/serialize.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/curves/bn254/bn254.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/native_verification_key.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/serialize/msgpack.hpp
  barretenberg/cpp/src/barretenberg/serialize/msgpack_apply.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/transcript/transcript.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_verification_key.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.hpp
  barretenberg/docs/docs/how_to_guides/how-to-solidity-verifier.md
  barretenberg/docs/scripts/build_docs.sh
  barretenberg/docs/versioned_docs/version-v0.87.0/how_to_guides/how-to-solidity-verifier.md
  barretenberg/ts/src/barretenberg/backend.ts
  barretenberg/ts/src/barretenberg/index.ts
  barretenberg/ts/src/barretenberg/verifier.ts
  barretenberg/ts/src/index.ts
  noir-projects/noir-protocol-circuits/bootstrap.sh
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/prover/proof_utils.ts
  yarn-project/bb-prover/src/verification_key/verification_key_data.ts
Labels: ci-no-fail-fast

#16717 feat(rollup): use optimized verifier
  barretenberg/acir_tests/bootstrap.sh
  noir-projects/noir-protocol-circuits/bootstrap.sh
Labels: ci-full

#16739 chore(ci): give prover-full 20 minutes
  yarn-project/end-to-end/bootstrap.sh
Labels: ci-barretenberg

#16779 chore(merge-train): update trains with no PR
  scripts/merge-train/merge-next.sh
Labels: ci-barretenberg

#16706 chore: audit the set relation of the ECCVM
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_set_relation_impl.hpp
Labels: bberg-int-audit

#16786 fix: AVM hints for Cpp must use current block gasFees rather than historical
  .test_patterns.yml
  yarn-project/end-to-end/src/e2e_prover/full.test.ts
  yarn-project/simulator/src/public/public_tx_simulator/public_tx_simulator.ts
  yarn-project/stdlib/src/avm/avm.ts
  yarn-project/stdlib/src/fees/transaction_fee.ts
Labels: ci-full

#16799 fix(sol): temporarily disable optimized verifier
  .test_patterns.yml
  noir-projects/noir-protocol-circuits/bootstrap.sh
  yarn-project/end-to-end/src/e2e_prover/full.test.ts
Labels: ci-full

#16767 refactor!: config and start options
  aztec-up/bin/aztec
  yarn-project/archiver/src/archiver/config.ts
  yarn-project/archiver/src/factory.ts
  yarn-project/aztec/package.json
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/cli/aztec_start_options.test.ts
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/aztec/src/cli/cmds/start_faucet.ts
  yarn-project/aztec/src/cli/cmds/start_node.ts
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
  yarn-project/aztec/src/cli/util.ts
  yarn-project/aztec/tsconfig.json
  yarn-project/blob-sink/src/server/config.ts
  yarn-project/bot/src/config.ts
  yarn-project/bot/src/factory.ts
  yarn-project/end-to-end/src/e2e_l1_publisher/e2e_l1_publisher.test.ts
  yarn-project/end-to-end/src/e2e_simple.test.ts
  yarn-project/end-to-end/src/e2e_synching.test.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/ethereum/src/l1_contract_addresses.ts
  yarn-project/ethereum/src/l1_reader.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/foundation/src/config/index.ts
  yarn-project/prover-node/src/prover-node-publisher.test.ts
  yarn-project/sequencer-client/src/publisher/config.ts
  yarn-project/yarn.lock
Labels: ci-full, ci-no-fail-fast

#16573 chore: audit wnaf relations in the ECCVM
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_wnaf_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/ecc_vm/ecc_wnaf_relation_impl.hpp
Labels: bberg-int-audit

#16852 chore: update deps
  barretenberg/docs/yarn.lock
  boxes/yarn.lock
  docs/yarn.lock
  playground/yarn.lock
  yarn-project/yarn.lock
Labels: hotfix

#16687 feat: ZK CIVC
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/circuit_checker/translator_circuit_checker.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.cpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/goblin/mock_circuits.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_fixed_vk.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/mega_honk.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
Labels: ci-full

#16868 feat: Ability to add validators directly using deposit function
  release-image/Dockerfile.dockerignore
  spartan/terraform/deploy-telemetry/main.tf
  yarn-project/aztec/src/bin/index.ts
  yarn-project/aztec/src/cli/cmds/start_archiver.ts
  yarn-project/aztec/src/cli/cmds/start_blob_sink.ts
  yarn-project/aztec/src/cli/cmds/start_node.ts
  yarn-project/aztec/src/cli/cmds/start_prover_broker.ts
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
  yarn-project/cli/package.json
  yarn-project/cli/public_include_metric_prefixes.json
  yarn-project/cli/src/cmds/l1/index.ts
  yarn-project/cli/src/cmds/l1/update_l1_validators.ts
  yarn-project/cli/src/config/chain_l2_config.ts
  yarn-project/cli/src/config/get_l1_config.ts
  yarn-project/cli/src/config/index.ts
  yarn-project/cli/tsconfig.json
  yarn-project/yarn.lock
Labels: hotfix

#16869 chore: Persist validation status in archiver
  yarn-project/archiver/src/archiver/archiver.test.ts
  yarn-project/archiver/src/archiver/archiver.ts
  yarn-project/archiver/src/archiver/archiver_store.ts
  yarn-project/archiver/src/archiver/archiver_store_test_suite.ts
  yarn-project/archiver/src/archiver/data_retrieval.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/block_store.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/kv_archiver_store.ts
  yarn-project/archiver/src/archiver/validation.test.ts
  yarn-project/archiver/src/archiver/validation.ts
  yarn-project/archiver/src/test/mock_l2_block_source.ts
  yarn-project/end-to-end/src/e2e_l1_publisher/e2e_l1_publisher.test.ts
  yarn-project/foundation/src/eth-signature/eth_signature.ts
  yarn-project/foundation/src/serialize/buffer_reader.ts
  yarn-project/p2p/src/mem_pools/attestation_pool/attestation_pool_test_suite.ts
  yarn-project/p2p/src/services/tx_collection/fast_tx_collection.ts
  yarn-project/p2p/src/services/tx_collection/tx_collection.ts
  yarn-project/p2p/src/services/tx_provider.ts
  yarn-project/prover-node/src/job/epoch-proving-job-data.test.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/slasher/src/watchers/attestations_block_watcher.test.ts
  yarn-project/slasher/src/watchers/attestations_block_watcher.ts
  yarn-project/stdlib/src/block/index.ts
  yarn-project/stdlib/src/block/l2_block.ts
  yarn-project/stdlib/src/block/l2_block_info.ts
  yarn-project/stdlib/src/block/l2_block_source.ts
  yarn-project/stdlib/src/block/published_l2_block.test.ts
  yarn-project/stdlib/src/block/published_l2_block.ts
  yarn-project/stdlib/src/block/test/l2_tips_store_test_suite.ts
  yarn-project/stdlib/src/block/validate_block_result.test.ts
  yarn-project/stdlib/src/block/validate_block_result.ts
  yarn-project/stdlib/src/interfaces/archiver.test.ts
  yarn-project/stdlib/src/interfaces/archiver.ts
  yarn-project/stdlib/src/interfaces/aztec-node.test.ts
  yarn-project/stdlib/src/p2p/block_attestation.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/stdlib/src/p2p/consensus_payload.ts
  yarn-project/stdlib/src/tests/mocks.ts
  yarn-project/stdlib/src/tx/content_commitment.ts
  yarn-project/stdlib/src/tx/partial_state_reference.ts
  yarn-project/stdlib/src/tx/proposed_block_header.ts
  yarn-project/stdlib/src/tx/state_reference.ts
  yarn-project/txe/src/state_machine/archiver.ts
  yarn-project/txe/src/state_machine/index.ts
Labels: ci-no-fail-fast

#17058 chore: Re-create cross chain messaging fix on v2
  .github/workflows/deploy-staging-networks.yml
  spartan/scripts/deploy_network.sh
  spartan/terraform/deploy-aztec-infra/main.tf
  spartan/terraform/deploy-aztec-infra/values/prover-resources-prod.yaml
  spartan/terraform/deploy-aztec-infra/values/rpc-resources-prod.yaml
  spartan/terraform/deploy-aztec-infra/values/validator-resources-prod.yaml
  spartan/terraform/deploy-aztec-infra/variables.tf
  spartan/terraform/gke-cluster/auto-updater-config.tf
  spartan/terraform/gke-cluster/cluster/main.tf
  spartan/terraform/gke-cluster/network-ingress.tf
  spartan/terraform/gke-cluster/outputs.tf
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/aztec.js/src/api/utils.ts
  yarn-project/aztec.js/src/contract/batch_call.ts
  yarn-project/aztec.js/src/utils/cross_chain.ts
  yarn-project/bot/src/config.ts
  yarn-project/bot/src/factory.ts
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/slasher/src/watchers/epoch_prune_watcher.ts
  yarn-project/stdlib/src/interfaces/aztec-node.test.ts
  yarn-project/stdlib/src/interfaces/aztec-node.ts
  yarn-project/stdlib/src/interfaces/pxe.test.ts
  yarn-project/stdlib/src/interfaces/pxe.ts
  yarn-project/stdlib/src/messaging/inbox_leaf.ts
Labels: ci-full

#17254 chore: bot keeps track of bridging claims in case of restart
  spartan/aztec-bot/values.yaml
  spartan/aztec-node/templates/_pod-template.yaml
  spartan/aztec-node/values.yaml
  yarn-project/aztec/src/cli/cmds/start_bot.ts
  yarn-project/bot/package.json
  yarn-project/bot/src/amm_bot.ts
  yarn-project/bot/src/bot.ts
  yarn-project/bot/src/config.ts
  yarn-project/bot/src/factory.ts
  yarn-project/bot/src/index.ts
  yarn-project/bot/src/runner.ts
  yarn-project/bot/src/store/bot_store.test.ts
  yarn-project/bot/src/store/bot_store.ts
  yarn-project/bot/src/store/index.ts
  yarn-project/bot/tsconfig.json
  yarn-project/end-to-end/src/e2e_bot.test.ts
  yarn-project/end-to-end/src/e2e_sequencer_config.test.ts
  yarn-project/yarn.lock
Labels: ci-no-fail-fast

#17194 fix: broker restarts on rollup change
  yarn-project/aztec/src/cli/cmds/start_prover_broker.ts
Labels: backport-to-v2

#17225 feat: check remote-signer is available
  yarn-project/aztec-node/src/aztec-node/config.ts
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/scripts/web3signer/docker-compose.yml
  yarn-project/end-to-end/src/composed/web3signer/e2e_multi_validator_node_key_store.test.ts
  yarn-project/end-to-end/src/composed/web3signer/integration_remote_signer.test.ts
  yarn-project/end-to-end/src/fixtures/web3signer.ts
  yarn-project/node-keystore/src/keystore_manager.test.ts
  yarn-project/node-keystore/src/keystore_manager.ts
  yarn-project/node-keystore/src/signer.ts
  yarn-project/prover-node/src/config.ts
  yarn-project/prover-node/src/factory.ts
Labels: backport-to-v2

#17285 fix: orchestrator and agents retry more when connecting to the broker
  yarn-project/aztec/src/cli/cmds/start_prover_agent.ts
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
Labels: backport-to-v2

#16895 chore: biggroup audit of lookup and rom tables
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/README.md
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_tables.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/memory/README.md
  barretenberg/cpp/src/barretenberg/stdlib/primitives/memory/twin_rom_table.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/non_native_group_generator.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/non_native_group_generator.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/rom_ram_logic.cpp
Labels: bberg-int-audit

#17278 fix(bb): oversight that disabled batch commits
  barretenberg/cpp/src/barretenberg/commitment_schemes/commitment_key.hpp
Labels: ci-full

#17115 chore: use CloudFlare R2 storage for snapshot storage
  ci3/bootstrap_ec2
  spartan/aztec-network/templates/full-node.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/archival-node.yaml
  spartan/aztec-snapshots/values.yaml
  spartan/environments/staging-ignition.env
  spartan/environments/staging-public.env
  spartan/environments/testnet.env
  spartan/scripts/deploy_network.sh
  spartan/scripts/setup_gcp_secrets.sh
  spartan/terraform/cloudflare/main.tf
  spartan/terraform/cloudflare/outputs.tf
  spartan/terraform/cloudflare/variables.tf
  spartan/terraform/deploy-aztec-infra/main.tf
  spartan/terraform/deploy-aztec-infra/values/rpc.yaml
  spartan/terraform/deploy-aztec-infra/variables.tf
  yarn-project/cli/src/config/chain_l2_config.ts
  yarn-project/stdlib/package.json
  yarn-project/stdlib/src/file-store/factory.ts
  yarn-project/stdlib/src/file-store/s3.ts
  yarn-project/yarn.lock
Labels: backport-to-v2

#17352 chore: change leaf index to Field
  noir-projects/noir-protocol-circuits/crates/reset-kernel-lib/src/reset/read_request.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/abis/block_rollup_public_inputs.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/components/block_rollup_public_inputs_composer.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/components/block_root_rollup_inputs_validator.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/tests/failures_tests.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/tests/mod.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/tests/rollup_fixture_builder.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/tx_base/tests/private_tx_base/end_blob_sponge_tests.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/tx_base/tests/private_tx_base/end_tree_snapshot_tests.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/tx_base/tests/private_tx_base/fee_tests.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/tx_base/tests/private_tx_base/mod.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/append_only_tree_snapshot.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/avm_circuit_public_inputs.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/nullifier_leaf_preimage.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/protocol_contract_leaf_preimage.nr
  noir-projects/noir-protocol-circuits/crates/types/src/data/public_data_tree_leaf_preimage.nr
  noir-projects/noir-protocol-circuits/crates/types/src/delayed_public_mutable/with_hash.nr
  noir-projects/noir-protocol-circuits/crates/types/src/merkle_tree/append_only_tree.nr
  noir-projects/noir-protocol-circuits/crates/types/src/merkle_tree/indexed_tree.nr
  noir-projects/noir-protocol-circuits/crates/types/src/merkle_tree/leaf_preimage.nr
  noir-projects/noir-protocol-circuits/crates/types/src/merkle_tree/membership.nr
  noir-projects/noir-protocol-circuits/crates/types/src/merkle_tree/merkle_tree.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/fixture_builder.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/fixtures/public_data_tree.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/merkle_tree_utils/single_subtree_merkle_tree.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/types/test_leaf_preimage.nr
Labels: ci-full
