Repository AztecProtocol/aztec-packages, pull requests merged in 2025-05, with the labels that each got.

#14019 fix: Use from pool if available
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
Labels: ci-full

#14022 feat: Verify tx proofs after all other validations
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-full

#14014 feat(alpha-testnet): fat block proposals
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/prover-node/src/job/epoch-proving-job.test.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.test.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/simulator/src/public/public_processor/public_processor.ts
  yarn-project/stdlib/src/p2p/block_proposal.test.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/stdlib/src/tests/mocks.ts
  yarn-project/validator-client/src/duties/validation_service.test.ts
  yarn-project/validator-client/src/duties/validation_service.ts
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
Labels: ci-full

#13987 feat: apply block header tx validator in p2p validations
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-full

#14075 fix: e2e_fees
  yarn-project/end-to-end/src/e2e_fees/private_payments.test.ts
Labels: ci-full

#14087 fix: Recover from block gaps in archiver
  yarn-project/archiver/src/archiver/archiver.test.ts
  yarn-project/archiver/src/archiver/archiver.ts
  yarn-project/archiver/src/archiver/archiver_store.ts
  yarn-project/archiver/src/archiver/archiver_store_test_suite.ts
  yarn-project/archiver/src/archiver/errors.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/block_store.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/kv_archiver_store.ts
  yarn-project/blob-sink/src/archive/blobscan_archive_client.ts
  yarn-project/blob-sink/src/archive/interface.ts
  yarn-project/blob-sink/src/client/http.ts
  yarn-project/blob-sink/src/client/interface.ts
  yarn-project/blob-sink/src/client/local.ts
Labels: ci-full

#13905 chore: more specific world state tree map size config
  barretenberg/cpp/src/barretenberg/nodejs_module/world_state/world_state.cpp
  yarn-project/blob-sink/src/client/config.ts
  yarn-project/blob-sink/src/server/factory.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/world-state/src/native/native_world_state.test.ts
  yarn-project/world-state/src/native/native_world_state.ts
  yarn-project/world-state/src/native/native_world_state_instance.ts
  yarn-project/world-state/src/synchronizer/config.ts
  yarn-project/world-state/src/synchronizer/factory.ts
Labels: ci-external

#14136 fix: use globalThis instead of self in PXE
  yarn-project/kv-store/src/indexeddb/store.ts
Labels: ci-external

#14143 chore: Merging alpha testnet changes back to master
  playground/src/components/contract/components/FunctionCard.tsx
  playground/src/components/sidebar/components/NetworkCongestionNotice.tsx
  playground/src/components/sidebar/components/NetworkSelector.tsx
  playground/src/hooks/useTransaction.tsx
  yarn-project/archiver/src/archiver/archiver.test.ts
  yarn-project/archiver/src/archiver/archiver.ts
  yarn-project/archiver/src/archiver/archiver_store.ts
  yarn-project/archiver/src/archiver/archiver_store_test_suite.ts
  yarn-project/archiver/src/archiver/errors.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/block_store.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/kv_archiver_store.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/message_store.ts
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_manual_rollback.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_test.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/client/interface.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
  yarn-project/p2p/src/msg_validators/tx_validator/block_header_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/data_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/double_spend_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/gas_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/metadata_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/phases_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/tx_proof_validator.ts
  yarn-project/p2p/src/services/dummy_service.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
  yarn-project/p2p/src/services/service.ts
  yarn-project/prover-node/src/job/epoch-proving-job.test.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.ts
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.test.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/simulator/src/public/public_processor/public_processor.ts
  yarn-project/stdlib/src/interfaces/aztec-node-admin.test.ts
  yarn-project/stdlib/src/interfaces/aztec-node-admin.ts
  yarn-project/stdlib/src/interfaces/world_state.ts
  yarn-project/stdlib/src/p2p/block_proposal.test.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/stdlib/src/tests/mocks.ts
  yarn-project/txe/src/state_machine/archiver.ts
  yarn-project/txe/src/state_machine/dummy_p2p_client.ts
  yarn-project/txe/src/state_machine/synchronizer.ts
  yarn-project/validator-client/src/duties/validation_service.test.ts
  yarn-project/validator-client/src/duties/validation_service.ts
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
  yarn-project/world-state/src/native/native_world_state.test.ts
  yarn-project/world-state/src/native/native_world_state.ts
  yarn-project/world-state/src/native/native_world_state_instance.ts
  yarn-project/world-state/src/synchronizer/server_world_state_synchronizer.ts
  yarn-project/world-state/src/world-state-db/merkle_tree_db.ts
Labels: ci-full

#14150 feat: RAM/ROM tables handler in SMT verification module
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_polynomials.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/data_structures.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/data_structures.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
Labels: product-security

#14239 chore: Added timestamp and message id debugging to p2p network
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/stdlib/src/p2p/block_attestation.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/stdlib/src/p2p/gossipable.test.ts
  yarn-project/stdlib/src/p2p/gossipable.ts
  yarn-project/stdlib/src/tx/tx.ts
Labels: ci-full

#14276 feat: Optionally publish txs in block proposals
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/sequencer-client/src/config.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/stdlib/src/interfaces/configs.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/validator-client/src/duties/validation_service.test.ts
  yarn-project/validator-client/src/duties/validation_service.ts
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
Labels: ci-full

#14281 feat!: Delay committee sampling by one epoch
  l1-contracts/src/core/libraries/TimeLib.sol
  l1-contracts/src/core/libraries/validator-selection/ValidatorSelectionLib.sol
  l1-contracts/test/RollupGetters.t.sol
  l1-contracts/test/fixtures/empty_block_1.json
  l1-contracts/test/fixtures/empty_block_2.json
  l1-contracts/test/fixtures/mixed_block_1.json
  l1-contracts/test/fixtures/mixed_block_2.json
  l1-contracts/test/fixtures/single_tx_block_1.json
  l1-contracts/test/fixtures/single_tx_block_2.json
  l1-contracts/test/governance/scenario/UpgradeGovernanceProposerTest.t.sol
  l1-contracts/test/governance/scenario/slashing/Slashing.t.sol
  l1-contracts/test/validator-selection/ValidatorSelection.t.sol
  l1-contracts/test/validator-selection/ValidatorSelectionBase.sol
  l1-contracts/test/validator-selection/setupEpoch.t.sol
  l1-contracts/test/validator-selection/setupEpoch.tree
  yarn-project/aztec.js/src/test/rollup_cheat_codes.ts
  yarn-project/end-to-end/src/composed/integration_l1_publisher.test.ts
  yarn-project/end-to-end/src/e2e_p2p/add_rollup.test.ts
  yarn-project/end-to-end/src/e2e_p2p/gossip_network.test.ts
  yarn-project/end-to-end/src/e2e_p2p/gossip_network_no_cheat.test.ts
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_p2p/rediscovery.test.ts
  yarn-project/end-to-end/src/e2e_p2p/reex.test.ts
  yarn-project/end-to-end/src/e2e_p2p/reqresp.test.ts
  yarn-project/end-to-end/src/e2e_p2p/slashing.test.ts
  yarn-project/end-to-end/src/e2e_p2p/upgrade_governance_proposer.test.ts
  yarn-project/end-to-end/src/e2e_p2p/validators_sentinel.test.ts
Labels: ci-full

#14352 feat!: Add client version to ENR
  yarn-project/aztec-node/src/aztec-node/config.ts
  yarn-project/aztec-node/src/aztec-node/server.test.ts
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/enr/generate-enr.ts
  yarn-project/p2p/src/services/discv5/discV5_service.ts
  yarn-project/p2p/src/services/discv5/discv5_service.test.ts
  yarn-project/p2p/src/test-helpers/make-test-p2p-clients.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/p2p/src/types/index.ts
  yarn-project/p2p/src/versioning.ts
  yarn-project/prover-node/src/prover-coordination/factory.ts
  yarn-project/stdlib/src/update-checker/update-checker.ts
  yarn-project/txe/src/state_machine/index.ts
Labels: ci-external

#14358 fix: fix oops
  .github/workflows/ci3.yml
  ci3/parallelise_strict
Labels: ci-full

#14327 fix: Handle historic blocks going out of sync
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/cached_content_addressed_tree_store.hpp
  barretenberg/cpp/src/barretenberg/world_state/world_state.cpp
  yarn-project/world-state/src/native/native_world_state.test.ts
Labels: ci-full

#14423 chore: Protocol breaking changes must now go to next branch.
  .github/workflows/ci3.yml
  .github/workflows/release-please.yml
  .test_patterns.yml
  barretenberg/cpp/bootstrap.sh
  ci3/bootstrap_ec2
  l1-contracts/bootstrap.sh
  l1-contracts/foundry.toml
  l1-contracts/test/shouting.t.sol
  release-please-config.json
Labels: ci-full

#14372 feat: Adds StarknetZK WASM bindings to bb.js
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/c_bind.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/c_bind.hpp
  barretenberg/exports.json
  barretenberg/ts/src/barretenberg/backend.ts
  barretenberg/ts/src/barretenberg_api/index.ts
  barretenberg/ts/src/main.ts
Labels: ci-external

#14470 chore: Cache base fees in the node
  yarn-project/sequencer-client/src/global_variable_builder/global_builder.ts
Labels: ci-full

#14449 feat: World State Benchmarks
  yarn-project/bootstrap.sh
  yarn-project/stdlib/src/block/body.ts
  yarn-project/stdlib/src/block/l2_block.ts
  yarn-project/stdlib/src/tx/tx_effect.ts
  yarn-project/txe/tsconfig.json
  yarn-project/world-state/src/native/bench_metrics.ts
  yarn-project/world-state/src/native/native_bench.test.ts
  yarn-project/world-state/src/test/utils.ts
Labels: bench, ci-full

#14498 fix: bug in `TxProvingResult` schema
  yarn-project/stdlib/src/tx/proven_tx.ts
Labels: ci-external

#14548 chore: Cache and persist block hashes
  yarn-project/archiver/src/archiver/kv_archiver_store/block_store.ts
  yarn-project/stdlib/src/block/l2_block.ts
Labels: ci-full

#14531 fix: Don't manually close stream on p2p/reqresp/goodbye
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.test.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.ts
  yarn-project/p2p/src/services/reqresp/protocols/goodbye.ts
  yarn-project/p2p/src/services/reqresp/reqresp.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: ci-external

#14437 fix: Attempt tree re-sync after application stop
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/cached_content_addressed_tree_store.hpp
  barretenberg/cpp/src/barretenberg/world_state/world_state.cpp
  barretenberg/cpp/src/barretenberg/world_state/world_state.hpp
  yarn-project/stdlib/src/p2p/consensus_payload.ts
  yarn-project/world-state/src/native/native_world_state.test.ts
Labels: ci-full
