Repository AztecProtocol/aztec-packages, pull requests merged in 2025-08, with the labels that each got.

#16156 chore: add a `PG_TAIL` proof type and queue type
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_to_constraint_buf.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/recursion_constraint.hpp
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/components/previous_kernel_validator.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_inner.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_reset.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_tail.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_tail_to_public.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/tests/previous_kernel_validator_builder/mod.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/private_kernel_data.nr
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
Labels: ci-full

#16163 chore(docs): Update testnet info
  docs/docs/try_testnet.md
  docs/src/preprocess/include_version.js
Labels: backport-to-master

#16186 chore: remove is_kernel from MegaCircuitBuilder
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_circuit_producer.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_circuit_builder.hpp
Labels: ci-full

#16219 chore(docs): update testnet version and add PXE URL in guides
  docs/docs/sandbox_to_testnet_guide.md
  docs/versioned_docs/version-v1.2.0/sandbox_to_testnet_guide.md
  docs/versioned_docs/version-v1.2.0/try_testnet.md
Labels: backport-to-master, generate-preview

#16046 feat(sol): keccak proofs are not padded
  barretenberg/acir_tests/bbjs-test/src/index.ts
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_contract.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_zk_contract.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_zk_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_zk_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_zk_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/test_utils/tamper_proof.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/mega_honk.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_honk.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
  barretenberg/sol/src/honk/BaseHonkVerifier.sol
  barretenberg/sol/src/honk/BaseZKHonkVerifier.sol
  barretenberg/sol/src/honk/CommitmentScheme.sol
  barretenberg/sol/src/honk/Fr.sol
  barretenberg/sol/src/honk/Transcript.sol
  barretenberg/sol/src/honk/ZKTranscript.sol
  barretenberg/sol/src/honk/utils.sol
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
  yarn-project/constants/src/constants.gen.ts
Labels: ci-full

#16257 chore(docs): enhance getting started guide with links and parameters
  docs/docs/developers/getting_started.md
  docs/docs/developers/guides/getting_started_on_testnet.md
  docs/docs/developers/reference/environment_reference/cli_wallet_reference.md
  docs/versioned_docs/version-v1.2.0/developers/guides/getting_started_on_testnet.md
  docs/versioned_docs/version-v1.2.0/developers/reference/environment_reference/cli_wallet_reference.md
  docs/versioned_docs/version-v1.2.0/developers/tutorials/codealong/first_fees.md
Labels: backport-to-master

#16327 chore(ci): experiment with non-linear history
  .github/workflows/ci3.yml
  .github/workflows/merge-train-create-pr.yml
  .github/workflows/merge-train-readme.md
  .github/workflows/merge-train-recreate.yml
  .github/workflows/squashed-pr-check.yml
  CI.md
  ci.sh
  scripts/merge-train/recreate-branch.sh
  scripts/merge-train/squash-pr.sh
Labels: ci-barretenberg

#16368 feat: Mocking for translator and eccvm proofs
  barretenberg/cpp/src/barretenberg/dsl/acir_format/avm2_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/special_public_inputs/special_public_inputs.hpp
Labels: ci-full

#15662 feat!: fiat-shamir AVM vk
  barretenberg/cpp/src/barretenberg/dsl/acir_format/avm2_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/goblin_field.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_goblin.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/prover.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/prover.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/verifier.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/proving_helper.cpp
Labels: ci-full

#16361 refactor: cleanup acir_tests and unused bb cli commands
  barretenberg/acir_tests/README.md
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/flows/all_cmds.sh
  barretenberg/acir_tests/flows/bb_prove_bbjs_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_bb_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_verify.sh
  barretenberg/acir_tests/flows/fail.sh
  barretenberg/acir_tests/flows/prove_and_verify.sh
  barretenberg/acir_tests/flows/prove_and_verify_program.sh
  barretenberg/acir_tests/flows/prove_then_verify.sh
  barretenberg/acir_tests/flows/prove_then_verify_client_ivc.sh
  barretenberg/acir_tests/flows/prove_then_verify_tube.sh
  barretenberg/acir_tests/flows/sol.sh
  barretenberg/acir_tests/flows/sol_honk.sh
  barretenberg/acir_tests/flows/sol_honk_zk.sh
  barretenberg/acir_tests/scripts/bb_prove.sh
  barretenberg/acir_tests/scripts/bb_prove_bbjs_verify.sh
  barretenberg/acir_tests/scripts/bb_prove_sol_verify.sh
  barretenberg/acir_tests/scripts/bb_tube_prove.sh
  barretenberg/acir_tests/scripts/bbjs_legacy_cli_prove.sh
  barretenberg/acir_tests/scripts/bbjs_prove.sh
  barretenberg/acir_tests/scripts/bbjs_prove_bb_verify.sh
  barretenberg/acir_tests/scripts/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/scripts/bench_acir_tests.sh
  barretenberg/acir_tests/scripts/browser_prove.sh
  barretenberg/acir_tests/scripts/run_bench.sh
  barretenberg/acir_tests/scripts/run_test.sh
  barretenberg/acir_tests/scripts/run_test_browser.sh
  barretenberg/acir_tests/sol-test/src/index.js
  barretenberg/cpp/scripts/find-bb
  barretenberg/cpp/src/barretenberg/api/api.hpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/gate_count.hpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/proof_surgeon.hpp
  ci3/docker_isolate
  noir-projects/gates_report.sh
  noir-projects/noir-protocol-circuits/bootstrap.sh
  noir-projects/noir-protocol-circuits/scripts/flamegraph.sh
  noir-projects/noir-protocol-circuits/scripts/run_bench.sh
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/prover/server/bb_prover.ts
  yarn-project/ivc-integration/src/prove_native.ts
Labels: ci-full

#16318 feat: fixed size decider without padding
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/boomerang_value_detection/graph_description_ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini_impl.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplonk.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/utils/mock_witness_generator.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/constants.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_contract.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_zk_contract.hpp
  barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_zk_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_zk_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/honk/composer/permutation_lib.hpp
  barretenberg/cpp/src/barretenberg/honk/library/grand_product_delta.hpp
  barretenberg/cpp/src/barretenberg/polynomials/gate_separator.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/relations/utils.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/oink_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_keys.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_keys.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/mega_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/witness_computation.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/witness_computation.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/prover.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/verifier.cpp
  barretenberg/sol/bootstrap.sh
  barretenberg/sol/src/honk/BaseHonkVerifier.sol
  barretenberg/sol/src/honk/BaseZKHonkVerifier.sol
Labels: ci-full

#16478 feat: clean up presets and upgrade to clang-20
  barretenberg/README.md
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/docs/Fuzzing.md
  barretenberg/cpp/scripts/analyze_vm_compile_time.sh
  barretenberg/cpp/scripts/benchmark.sh
  barretenberg/cpp/scripts/benchmark_client_ivc.sh
  barretenberg/cpp/scripts/benchmark_example_ivc_flow_remote.sh
  barretenberg/cpp/scripts/benchmark_field_ops_percentage.sh
  barretenberg/cpp/scripts/benchmark_protogalaxy.sh
  barretenberg/cpp/scripts/benchmark_remote.sh
  barretenberg/cpp/scripts/benchmarks.sh
  barretenberg/cpp/scripts/compare_branch_vs_baseline.sh
  barretenberg/cpp/scripts/compare_branch_vs_baseline_remote.sh
  barretenberg/cpp/scripts/lmdblib_tests.sh
  barretenberg/cpp/scripts/merkle_tree_tests.sh
  barretenberg/cpp/scripts/native-preset-build-dir
  barretenberg/cpp/scripts/run_test.sh
  barretenberg/cpp/scripts/test_coverage.sh
  barretenberg/cpp/scripts/world_state_tests.sh
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/ipa_recursive.test.cpp
  barretenberg/cpp/src/barretenberg/nodejs_module/util/message_processor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/bytecode_manager.hpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/bytecode_manager.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/emit_unencrypted_log.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/simulation_helper.cpp
  barretenberg/cpp/src/barretenberg/vm2/tooling/stats.hpp
  bootstrap.sh
  build-images/README.md
  build-images/bootstrap.sh
  build-images/src/Dockerfile
  ci3/aws/ami_id_amd64
  ci3/aws/ami_id_arm64
Labels: arm64-ci, ci-full

#16462 fix: enforce from check on all interactions
  yarn-project/aztec.js/src/contract/base_contract_interaction.ts
  yarn-project/aztec.js/src/contract/contract.test.ts
  yarn-project/aztec.js/src/contract/contract_function_interaction.ts
  yarn-project/end-to-end/src/bench/client_flows/transfers.test.ts
  yarn-project/end-to-end/src/composed/docs_examples.test.ts
  yarn-project/end-to-end/src/e2e_2_pxes.test.ts
  yarn-project/end-to-end/src/e2e_block_building.test.ts
  yarn-project/end-to-end/src/e2e_card_game.test.ts
  yarn-project/end-to-end/src/shared/uniswap_l1_l2.ts
Labels: ci-full, ci-no-fail-fast

#16484 chore: update bb-versions.json to Noir v1.0.0-beta.11
  barretenberg/bbup/bb-versions.json
Labels: C-bb-bin

#16444 chore: refactor `ClientIVC` and `MockCircuitProducer`
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_execute.hpp
  barretenberg/cpp/src/barretenberg/benchmark/client_ivc_bench/client_ivc.bench.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_circuit_producer.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_kernel_pinning.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/test_bench_shared.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/client_ivc_verifier/client_ivc_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_proving_key.hpp
  barretenberg/ts/src/barretenberg/backend.ts
  barretenberg/ts/src/barretenberg/index.ts
Labels: ci-full

#16529 chore: Use L1TxUtils instead of raw client
  yarn-project/end-to-end/src/e2e_p2p/slash_veto_demo.test.ts
Labels: ci-external

#16461 chore: Removed pruning of the duplicate connections
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
Labels: ci-external

#16563 chore: remove the early returns from `complete_kernel_circuit_logic'
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
Labels: ci-full

#16547 feat!: Protogalaxy accumulator hash consistency check
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/common/assert.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/pg_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/honk/types/public_inputs_type.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_prover_impl.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_key.hpp
  barretenberg/cpp/src/barretenberg/stdlib/special_public_inputs/special_public_inputs.hpp
  barretenberg/cpp/src/barretenberg/stdlib/special_public_inputs/special_public_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_verification_key.hpp
Labels: ci-full

#16570 fix: squash commit attribution and fork behaviour
  scripts/merge-train/squash-pr.sh
Labels: ci-barretenberg

#16623 fix: solidity gate challenge generation
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_contract.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_zk_contract.hpp
  barretenberg/sol/src/honk/Transcript.sol
  barretenberg/sol/src/honk/ZKTranscript.sol
Labels: ci-full, ci-barretenberg

#16621 refactor: staking queue config now includes max value
  l1-contracts/.gitignore
  l1-contracts/foundry.toml
  l1-contracts/script/Migration.s.sol
  l1-contracts/script/registration_data.json
  l1-contracts/src/core/libraries/StakingQueue.sol
  l1-contracts/src/core/libraries/compressed-data/StakingQueueConfig.sol
  l1-contracts/src/core/libraries/rollup/StakingLib.sol
  l1-contracts/src/mock/MultiAdder.sol
  l1-contracts/test/compression/StakingQueueConfig.t.sol
  l1-contracts/test/harnesses/TestConstants.sol
  l1-contracts/test/staking/flushEntryQueue.t.sol
  l1-contracts/test/staking/invalidDeposit.t.sol
  l1-contracts/test/staking/tmnt221.t.sol
  l1-contracts/test/staking/updateStakingQueueConfig.t.sol
  yarn-project/ethereum/src/config.ts
  yarn-project/ethereum/src/contracts/rollup.ts
  yarn-project/ethereum/src/deploy_l1_contracts.test.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
Labels: T-bug, A-security

#16503 feat: ECCVM Fuzzer
  barretenberg/cpp/src/barretenberg/eccvm/README_FUZZERS.md
  barretenberg/cpp/src/barretenberg/eccvm/eccvm.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_trace_checker.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_trace_checker.hpp
  barretenberg/security/Tooling.md
Labels: product-security

#16647 chore: Validate L1 config in ts-land
  l1-contracts/src/core/libraries/Errors.sol
  l1-contracts/src/core/slashing/TallySlashingProposer.sol
  yarn-project/aztec/src/cli/chain_l2_config.ts
  yarn-project/aztec/src/sandbox/sandbox.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_invalidate_block.test.ts
  yarn-project/end-to-end/src/e2e_p2p/add_rollup.test.ts
  yarn-project/end-to-end/src/e2e_p2p/data_withholding_slash.test.ts
  yarn-project/end-to-end/src/e2e_p2p/gossip_network.test.ts
  yarn-project/end-to-end/src/e2e_p2p/inactivity_slash.test.ts
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_p2p/reqresp.test.ts
  yarn-project/end-to-end/src/e2e_p2p/reqresp_no_handshake.test.ts
  yarn-project/end-to-end/src/e2e_p2p/slash_veto_demo.test.ts
  yarn-project/end-to-end/src/e2e_p2p/upgrade_governance_proposer.test.ts
  yarn-project/end-to-end/src/e2e_p2p/valid_epoch_pruned.test.ts
  yarn-project/end-to-end/src/e2e_p2p/validators_sentinel.test.ts
  yarn-project/end-to-end/src/fixtures/snapshot_manager.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/end-to-end/src/spartan/upgrade_rollup_version.test.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/ethereum/src/contracts/tally_slashing_proposer.test.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
  yarn-project/ethereum/src/queries.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/slasher/src/slash_round_monitor.ts
Labels: ci-no-fail-fast
