Repository AztecProtocol/aztec-packages, pull requests merged in 2025-02, with the labels that each got.

#11044 feat: static ip for dashboard
  .github/workflows/metrics-deploy.yml
  spartan/aztec-network/templates/_helpers.tpl
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/eth/eth-beacon.yaml
  spartan/aztec-network/templates/eth/eth-execution.yaml
  spartan/aztec-network/templates/eth/eth-validator.yaml
  spartan/aztec-network/templates/faucet.yaml
  spartan/aztec-network/templates/prover-agent.yaml
  spartan/aztec-network/templates/prover-broker.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/templates/pxe.yaml
  spartan/aztec-network/templates/transaction-bot.yaml
  spartan/aztec-network/templates/validator.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/exp-1.yaml
  spartan/aztec-network/values/exp-2.yaml
  spartan/aztec-network/values/rc-1.yaml
  spartan/metrics/copy-dashboard.sh
  spartan/metrics/install-kind.sh
  spartan/metrics/install-prod.sh
  spartan/metrics/values.tmp.yaml
  spartan/metrics/values/kind.yaml
  spartan/metrics/values/prod.yaml
  spartan/terraform/deploy-metrics/main.tf
  spartan/terraform/deploy-metrics/outputs.tf
  spartan/terraform/deploy-metrics/variables.tf
  spartan/terraform/deploy-release/main.tf
  spartan/terraform/gke-cluster/cluster/main.tf
  spartan/terraform/gke-cluster/iam.tf
Labels: network-all

#11672 chore(spartan): remove hardcoded keys and addresses - derive all from mnemonic
  spartan/aztec-network/eth-devnet/create.sh
  spartan/aztec-network/files/config/config-validator-env.sh
  spartan/aztec-network/files/config/deploy-l1-contracts.sh
  spartan/aztec-network/files/config/get-private-key.sh
  spartan/aztec-network/files/config/get-validator-addresses.sh
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/templates/scripts-configmap.yaml
  spartan/aztec-network/templates/validator-keys.yaml
  spartan/aztec-network/templates/validator.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/1-validator-with-proving.yaml
  spartan/aztec-network/values/1-validators-public.yaml
  spartan/aztec-network/values/1-validators.yaml
  spartan/aztec-network/values/16-validators-with-metrics.yaml
  spartan/aztec-network/values/16-validators.yaml
  spartan/aztec-network/values/3-validators-with-metrics.yaml
  spartan/aztec-network/values/3-validators.yaml
  spartan/aztec-network/values/4-validators-with-metrics.yaml
  spartan/aztec-network/values/48-validators.yaml
  spartan/aztec-network/values/ci.yaml
  spartan/aztec-network/values/exp-1.yaml
  spartan/aztec-network/values/exp-2.yaml
  spartan/aztec-network/values/multicloud-demo.yaml
  spartan/aztec-network/values/rc-1.yaml
  spartan/aztec-network/values/rc-2.yaml
  spartan/aztec-network/values/release-devnet.yaml
  spartan/scripts/generate_devnet_config.sh
  spartan/scripts/test_kind.sh
  yarn-project/cli/src/cmds/l1/deploy_l1_contracts.ts
  yarn-project/cli/src/cmds/l1/index.ts
  yarn-project/cli/src/utils/aztec.ts
Labels: network-all

#11656 chore: improve boxes
  boxes/bootstrap.sh
  boxes/boxes/react/webpack.config.js
  boxes/boxes/vite/.env
  boxes/boxes/vite/.gitignore
  boxes/boxes/vite/package.json
  boxes/boxes/vite/playwright.config.ts
  boxes/boxes/vite/src/config.ts
  boxes/boxes/vite/src/main.tsx
  boxes/boxes/vite/tests/browser.spec.ts
  boxes/boxes/vite/tests/node.test.ts
  boxes/docker-compose.yml
  boxes/yarn.lock
  gaztec/package.json
  gaztec/src/aztecEnv.ts
  gaztec/src/components/contract/components/deployContractDialog.tsx
  gaztec/src/components/contract/contract.tsx
  gaztec/src/components/contract/dropzone.css
  gaztec/src/components/home/home.tsx
  gaztec/src/components/logPanel/logPanel.tsx
  gaztec/src/components/sidebar/components/txsPanel.tsx
  gaztec/src/components/sidebar/sidebar.tsx
  gaztec/yarn.lock
  yarn-project/aztec.js/webpack.config.js
  yarn-project/bootstrap.sh
  yarn-project/noir-protocol-circuits-types/src/scripts/generate_client_artifacts_helper.ts
  yarn-project/package.json
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/pxe/src/synchronizer/synchronizer.ts
Labels: e2e-all

#11691 fix: barretenberg/stdlib/logic bugs (redo)
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/composer/composer_lib.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/plookup_tables.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/types.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/uint.hpp
Labels: e2e-all

#11712 fix: solidity verifier caching
  l1-contracts/bootstrap.sh
Labels: e2e-all

#11714 chore: no rbac on kind
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/deploy-l1-verifier.yaml
  spartan/aztec-network/templates/faucet.yaml
  spartan/aztec-network/templates/prover-agent.yaml
  spartan/aztec-network/templates/prover-broker.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/templates/pxe.yaml
  spartan/aztec-network/templates/rbac.yaml
  spartan/aztec-network/templates/setup-l2-contracts.yaml
  spartan/aztec-network/templates/transaction-bot.yaml
  spartan/aztec-network/templates/validator.yaml
Labels: network-all

#11596 feat!: leonidas library
  docs/docs/guides/developer_guides/js_apps/test.md
  l1-contracts/src/core/Rollup.sol
  l1-contracts/src/core/RollupCore.sol
  l1-contracts/src/core/ValidatorSelection.sol
  l1-contracts/src/core/interfaces/IRollup.sol
  l1-contracts/src/core/interfaces/IStaking.sol
  l1-contracts/src/core/interfaces/IValidatorSelection.sol
  l1-contracts/src/core/libraries/Errors.sol
  l1-contracts/src/core/libraries/RollupLibs/ValidationLib.sol
  l1-contracts/src/core/libraries/ValidatorSelectionLib/ValidatorSelectionLib.sol
  l1-contracts/src/core/libraries/staking/StakingLib.sol
  l1-contracts/src/periphery/Forwarder.sol
  l1-contracts/src/periphery/SlashPayload.sol
  l1-contracts/test/Forwarder.t.sol
  l1-contracts/test/Rollup.t.sol
  l1-contracts/test/base/Base.sol
  l1-contracts/test/fees/FeeRollup.t.sol
  l1-contracts/test/governance/governance-proposer/executeProposal.t.sol
  l1-contracts/test/governance/governance-proposer/mocks/Fakerollup.sol
  l1-contracts/test/governance/governance-proposer/vote.t.sol
  l1-contracts/test/harnesses/ValidatorSelection.sol
  l1-contracts/test/portals/UniswapPortal.t.sol
  l1-contracts/test/staking/deposit.t.sol
  l1-contracts/test/staking/finaliseWithdraw.t.sol
  l1-contracts/test/staking/initiateWithdraw.t.sol
  l1-contracts/test/staking/slash.t.sol
  l1-contracts/test/validator-selection/ValidatorSelection.t.sol
  yarn-project/epoch-cache/src/epoch_cache.ts
  yarn-project/ethereum/src/contracts/rollup.ts
Labels: network-all

#11741 chore: Use batch p2p reqresp for requesting txs in prover node
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/circuit-types/src/interfaces/aztec-node.test.ts
  yarn-project/circuit-types/src/interfaces/aztec-node.ts
  yarn-project/circuit-types/src/interfaces/prover-coordination.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/prover-node/src/prover-node.test.ts
  yarn-project/prover-node/src/prover-node.ts
  yarn-project/txe/src/node/txe_node.ts
Labels: e2e-p2p

#8022 feat!: introduce `WithHash<T>` + use it in `PublicImmutable`
  docs/docs/migration_notes.md
  noir-projects/aztec-nr/aztec/src/state_vars/public_immutable.nr
  noir-projects/aztec-nr/aztec/src/utils/mod.nr
  noir-projects/aztec-nr/aztec/src/utils/with_hash.nr
  noir-projects/aztec-nr/compressed-string/src/field_compressed_string.nr
  noir-projects/noir-contracts/contracts/amm_contract/src/config.nr
  noir-projects/noir-contracts/contracts/app_subscription_contract/src/main.nr
  noir-projects/noir-contracts/contracts/claim_contract/src/main.nr
  noir-projects/noir-contracts/contracts/crowdfunding_contract/src/main.nr
  noir-projects/noir-contracts/contracts/docs_example_contract/src/types/leader.nr
  noir-projects/noir-contracts/contracts/fpc_contract/src/config.nr
  noir-projects/noir-contracts/contracts/fpc_contract/src/main.nr
  noir-projects/noir-contracts/contracts/test_contract/src/main.nr
  noir-projects/noir-contracts/contracts/test_contract/src/test.nr
  noir-projects/noir-contracts/contracts/token_bridge_contract/src/main.nr
  yarn-project/foundation/src/fields/fields.ts
  yarn-project/types/src/abi/contract_artifact.ts
Labels: C-aztec.nr, team-fairies

#11761 chore: Better bundling for bb.js, remove aztec.js bundling
  barretenberg/acir_tests/browser-test-app/package.json
  barretenberg/acir_tests/browser-test-app/serve.json
  barretenberg/acir_tests/browser-test-app/serve.st.json
  barretenberg/acir_tests/browser-test-app/webpack.config.js
  barretenberg/ts/package.json
  barretenberg/ts/src/barretenberg_wasm/fetch_code/browser/barretenberg-threads.ts
  barretenberg/ts/src/barretenberg_wasm/fetch_code/browser/barretenberg.ts
  barretenberg/ts/src/barretenberg_wasm/fetch_code/browser/index.ts
  barretenberg/ts/src/barretenberg_wasm/fetch_code/wasm-module.d.ts
  barretenberg/ts/webpack.config.js
  barretenberg/ts/yarn.lock
  boxes/boxes/react/package.json
  boxes/boxes/react/webpack.config.js
  boxes/boxes/vanilla/package.json
  boxes/boxes/vanilla/webpack.config.js
  boxes/boxes/vite/package.json
  boxes/boxes/vite/vite.config.ts
  boxes/yarn.lock
  playground/package.json
  playground/src/aztecEnv.ts
  playground/vite.config.ts
  playground/yarn.lock
  yarn-project/.gitignore
  yarn-project/accounts/tsconfig.dest.json
  yarn-project/aztec.js/package.json
  yarn-project/aztec.js/package.local.json
  yarn-project/aztec.js/src/api/cheat_codes.ts
  yarn-project/aztec.js/src/api/ethereum.ts
  yarn-project/aztec.js/src/api/ethereum/anvil_test_watcher.ts
  yarn-project/aztec.js/src/api/ethereum/chain_monitor.ts
  yarn-project/aztec.js/src/api/ethereum/cheat_codes.ts
  yarn-project/aztec.js/src/api/ethereum/index.ts
  yarn-project/aztec.js/src/api/ethereum/l1_contracts.ts
  yarn-project/aztec.js/src/api/ethereum/portal_manager.ts
  yarn-project/aztec.js/src/api/log.ts
  yarn-project/aztec.js/src/entrypoint/default_multi_call_entrypoint.ts
  yarn-project/aztec.js/src/fee/fee_juice_payment_method_with_claim.ts
  yarn-project/aztec.js/src/index.ts
  yarn-project/aztec.js/src/utils/aztec_cheatcodes.ts
  yarn-project/aztec.js/src/utils/index.ts
  yarn-project/aztec.js/src/utils/node.ts
  yarn-project/aztec.js/src/wallet/index.ts
  yarn-project/aztec.js/tsconfig.dest.json
  yarn-project/aztec.js/webpack.config.js
  yarn-project/bootstrap.sh
  yarn-project/circuit-types/tsconfig.dest.json
  yarn-project/circuits.js/tsconfig.dest.json
  yarn-project/cli/src/cmds/l1/update_l1_validators.ts
  yarn-project/end-to-end/package.json
  yarn-project/end-to-end/src/e2e_epochs.test.ts
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_pruned_blocks.test.ts
  yarn-project/end-to-end/src/spartan/4epochs.test.ts
  yarn-project/end-to-end/src/spartan/gating-passive.test.ts
  yarn-project/end-to-end/src/spartan/reorg.test.ts
  yarn-project/end-to-end/src/spartan/utils.ts
  yarn-project/end-to-end/src/web/index.html
  yarn-project/end-to-end/webpack.config.js
  yarn-project/entrypoints/tsconfig.dest.json
  yarn-project/yarn.lock
Labels: e2e-all, e2e-browser

#11759 chore: sepolia mnemonic, e2e & ignition chain
  .github/workflows/network-deploy.yml
  .github/workflows/nightly-kind-test.yml
  playground/yarn.lock
  spartan/aztec-network/files/config/get-private-key.sh
  spartan/aztec-network/files/config/get-validator-addresses.sh
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/ci-sepolia.yaml
  spartan/aztec-network/values/ignition-reth.yaml
  spartan/aztec-network/values/ignition-testnet.yaml
  spartan/aztec-network/values/rc-2.yaml
  spartan/aztec-network/values/sepolia-3-validators-with-metrics.yaml
  spartan/scripts/deploy_kind.sh
  spartan/scripts/test_kind.sh
  spartan/terraform/deploy-release/main.tf
  spartan/terraform/deploy-release/variables.tf
  yarn-project/archiver/src/archiver/config.ts
  yarn-project/aztec-node/src/aztec-node/config.ts
  yarn-project/blob-sink/src/client/http.test.ts
  yarn-project/blob-sink/src/client/http.ts
  yarn-project/cli/src/utils/aztec.ts
  yarn-project/end-to-end/src/spartan/4epochs.test.ts
  yarn-project/end-to-end/src/spartan/utils.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
  yarn-project/ethereum/src/l1_tx_utils.ts
  yarn-project/foundation/src/config/index.ts
  yarn-project/sequencer-client/src/publisher/config.ts
Labels: network-all

#11307 feat(spartan): blob sink in spartan
  .github/workflows/ci.yml
  spartan/aztec-network/templates/_helpers.tpl
  spartan/aztec-network/templates/blob-sink.yaml
  spartan/aztec-network/templates/boot-node.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/templates/validator.yaml
  spartan/aztec-network/values.yaml
  spartan/scripts/deploy_kind.sh
  spartan/scripts/test_kind.sh
  yarn-project/aztec/src/cli/aztec_start_action.ts
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/aztec/src/cli/cmds/start_blob_sink.ts
  yarn-project/blob-sink/src/client/http.ts
  yarn-project/blob-sink/src/server/server.test.ts
  yarn-project/blob-sink/src/server/server.ts
  yarn-project/foundation/src/serialize/field_reader.ts
Labels: network-all

#11590 chore(spartan): update ethereum external host values
  spartan/aztec-network/templates/_helpers.tpl
  spartan/aztec-network/templates/eth/eth-beacon.yaml
  spartan/aztec-network/templates/eth/eth-execution.yaml
  spartan/aztec-network/templates/eth/eth-validator.yaml
  spartan/aztec-network/templates/faucet.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/ci-sepolia.yaml
  spartan/aztec-network/values/ignition-testnet.yaml
  spartan/aztec-network/values/rc-2.yaml
  spartan/aztec-network/values/sepolia-3-validators-with-metrics.yaml
  spartan/aztec-network/values/sepolia-48-validators-with-metrics.yaml
  spartan/aztec-network/values/sepolia-48-validators-with-proving-and-metrics.yaml
  spartan/scripts/deploy_kind.sh
  spartan/terraform/deploy-release/main.tf
  spartan/terraform/multicloud-deploy/main.tf
Labels: network-all

#11786 fix: Add missing return in main
  barretenberg/cpp/src/barretenberg/bb/main.cpp
  yarn-project/ivc-integration/src/browser_client_ivc_integration.test.ts
  yarn-project/ivc-integration/src/native_client_ivc_integration.test.ts
  yarn-project/ivc-integration/src/wasm_client_ivc_integration.test.ts
Labels: e2e-all, e2e

#11854 fix: beacon chain doesn't eat mainframe
  spartan/aztec-network/values.yaml
Labels: network-all

#11823 feat: Trust tree roots from the AVM in public base
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/base/private_base_rollup.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/base/public_base_rollup.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/base/state_diff_hints.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/tree_snapshots.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/fixture_builder.nr
  yarn-project/circuits.js/src/structs/rollup/base_rollup_hints.ts
  yarn-project/circuits.js/src/structs/rollup/state_diff_hints.test.ts
  yarn-project/circuits.js/src/structs/rollup/state_diff_hints.ts
  yarn-project/circuits.js/src/tests/factories.ts
  yarn-project/noir-protocol-circuits-types/src/conversion/server.ts
  yarn-project/prover-client/src/mocks/test_context.ts
  yarn-project/prover-client/src/orchestrator/block-building-helpers.ts
  yarn-project/prover-client/src/orchestrator/orchestrator_errors.test.ts
  yarn-project/prover-client/src/orchestrator/orchestrator_mixed_blocks.test.ts
  yarn-project/prover-client/src/orchestrator/orchestrator_single_blocks.test.ts
  yarn-project/prover-client/src/orchestrator/orchestrator_workflow.test.ts
Labels: e2e-all

#11886 fix: cleanup also post test_kind.sh
  spartan/scripts/test_kind.sh
Labels: network-all

#11649 fix: smt_verification: negative bitvecs, changed gates indicies. acir_formal_proofs: noir-style signed division
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/formal_proofs.cpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/helpers.cpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/helpers.hpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/helpers.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/README.md
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bvterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
Labels: product-security

#11818 feat: add undici
  yarn-project/aztec/src/cli/cmds/start_prover_agent.ts
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
  yarn-project/foundation/package.json
  yarn-project/foundation/src/json-rpc/client/fetch.ts
  yarn-project/foundation/src/json-rpc/client/safe_json_rpc_client.ts
  yarn-project/foundation/src/json-rpc/client/undici.ts
  yarn-project/telemetry-client/src/wrappers/fetch.ts
  yarn-project/yarn.lock
Labels: e2e-all, network-all

#11878 chore: use RelationChecker in relation correctness tests and add Translator interleaving test
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.hpp
  barretenberg/cpp/src/barretenberg/plonk_honk_shared/relation_checker.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/relation_correctness.test.cpp
Labels: crypto

#11920 fix: Empty blocks can now be unwound
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/indexed_tree/content_addressed_indexed_tree.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/cached_content_addressed_tree_store.hpp
  yarn-project/world-state/src/native/native_world_state.test.ts
Labels: e2e-all, network-all

#11692 chore: Use realistic size Client IVC proofs during simulations
  yarn-project/circuits.js/src/structs/client_ivc_proof.ts
  yarn-project/pxe/src/kernel_prover/kernel_prover.ts
Labels: e2e-all, network-all

#11739 feat: Native world state now supports checkpointing
  barretenberg/cpp/scripts/merkle_tree_tests.sh
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/append_only_tree/content_addressed_append_only_tree.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/indexed_tree/content_addressed_indexed_tree.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/indexed_tree/content_addressed_indexed_tree.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/cached_content_addressed_tree_store.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/content_addressed_cache.hpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/node_store/content_addressed_cache.test.cpp
  barretenberg/cpp/src/barretenberg/crypto/merkle_tree/test_fixtures.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/world_state/world_state.cpp
  barretenberg/cpp/src/barretenberg/nodejs_module/world_state/world_state.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/world_state/world_state_message.hpp
  barretenberg/cpp/src/barretenberg/world_state/world_state.cpp
  barretenberg/cpp/src/barretenberg/world_state/world_state.hpp
  yarn-project/circuit-types/src/interfaces/merkle_tree_operations.ts
  yarn-project/circuits.js/src/structs/public_data_write.ts
  yarn-project/world-state/src/native/merkle_trees_facade.ts
  yarn-project/world-state/src/native/message.ts
  yarn-project/world-state/src/native/native_world_state.test.ts
  yarn-project/world-state/src/native/world_state_ops_queue.ts
Labels: e2e-all, network-all

#11965 chore: unify webpack dev server versions
  barretenberg/acir_tests/browser-test-app/package.json
  barretenberg/ts/package.json
  barretenberg/ts/yarn.lock
  boxes/boxes/react/package.json
  boxes/contract-only/package.json
  boxes/yarn.lock
  noir/noir-repo/compiler/wasm/package.json
  noir/noir-repo/yarn.lock
  yarn-project/ivc-integration/package.json
  yarn-project/noir-bb-bench/package.json
  yarn-project/noir-bb-bench/webpack.config.js
  yarn-project/yarn.lock
Labels: e2e-all

#11956 fix: remove serial queue in broker facade
  yarn-project/prover-client/src/mocks/test_context.ts
  yarn-project/prover-client/src/proving_broker/broker_prover_facade.ts
  yarn-project/prover-client/src/test/mock_prover.ts
Labels: e2e-all, network-all

#11964 chore: revive browser test before killing it
  yarn-project/end-to-end/src/shared/browser.ts
Labels: e2e-all

#11986 chore: op wires index from 0
  barretenberg/cpp/src/barretenberg/relations/ecc_op_queue_relation.hpp
  barretenberg/cpp/src/barretenberg/trace_to_polynomials/trace_to_polynomials.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_proving_key.cpp
Labels: crypto

#12020 chore(ci3): label handling
  .github/workflows/ci-arm.yml
  .github/workflows/ci3.yml
  .github/workflows/publish-aztec-packages.yml
Labels: e2e-all

#12003 chore: structured polys in Translator
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_prover.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.test.cpp
Labels: crypto

#12057 fix(e2ep2p): excessive discovery warnings in e2e test
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_p2p/rediscovery.test.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
Labels: e2e-p2p

#12041 fix: Ensure a clean LMDB wrapper shutdown
  barretenberg/cpp/src/barretenberg/messaging/dispatcher.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/lmdb_store/lmdb_store_wrapper.cpp
  barretenberg/cpp/src/barretenberg/nodejs_module/lmdb_store/lmdb_store_wrapper.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/util/message_processor.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/world_state/world_state.cpp
  yarn-project/kv-store/src/lmdb-v2/close.test.ts
Labels: e2e-all, network-all

#11822 refactor: remove `addNullifiedNote` from pxe
  yarn-project/aztec.js/src/wallet/base_wallet.ts
  yarn-project/circuit-types/src/interfaces/pxe.test.ts
  yarn-project/circuit-types/src/interfaces/pxe.ts
  yarn-project/end-to-end/src/e2e_2_pxes.test.ts
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/pxe/src/simulator_oracle/simulator_oracle.test.ts
  yarn-project/simulator/src/client/private_execution.test.ts
  yarn-project/simulator/src/client/simulator.test.ts
  yarn-project/simulator/src/client/simulator.ts
Labels: e2e-all

#12066 refactor: function macros cleanup
  noir-projects/aztec-nr/aztec/src/context/call_interfaces.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/abi_export.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/call_interface_stubs.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/interfaces.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/mod.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/stub_registry.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/utils.nr
  noir-projects/aztec-nr/aztec/src/macros/mod.nr
  noir-projects/aztec-nr/aztec/src/macros/utils.nr
Labels: e2e-all

#12105 chore: Provide defaults for bb and acvm in release image
  release-image/Dockerfile
Labels: e2e-all, network-all

#11817 feat: optimizing `SharedMutable` storage slots
  barretenberg/cpp/src/barretenberg/vm/avm/trace/trace.cpp
  barretenberg/cpp/src/barretenberg/vm/aztec_constants.hpp
  l1-contracts/src/core/libraries/ConstantsGen.sol
  noir-projects/aztec-nr/aztec/src/state_vars/shared_mutable.nr
  noir-projects/noir-contracts/contracts/test_contract/src/test.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-init/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-inner/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/components/private_call_data_validator/validate_contract_address.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/components/private_kernel_circuit_output_validator.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/components/private_kernel_circuit_public_inputs_composer.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-reset/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-tail-to-public/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-tail/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-base-private/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-base-public/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-block-merge/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-block-root/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-merge/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-root/Prover.toml
  noir-projects/noir-protocol-circuits/crates/types/src/abis/private_kernel/private_call_data.nr
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/mod.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/scheduled_delay_change.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/scheduled_delay_change/test.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/scheduled_value_change.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/scheduled_value_change/test.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/shared_mutable_values.nr
  noir-projects/noir-protocol-circuits/crates/types/src/shared_mutable/shared_mutable_values/test.nr
  noir-projects/noir-protocol-circuits/crates/types/src/tests/fixture_builder.nr
  yarn-project/bb-prover/src/avm_proving_tests/avm_contract_updates.test.ts
  yarn-project/circuits.js/package.json
  yarn-project/circuits.js/src/structs/kernel/private_call_data.ts
  yarn-project/circuits.js/src/structs/shared_mutable/index.ts
  yarn-project/circuits.js/src/structs/shared_mutable/scheduled_delay_change.test.ts
  yarn-project/circuits.js/src/structs/shared_mutable/scheduled_delay_change.ts
  yarn-project/circuits.js/src/structs/shared_mutable/scheduled_value_change.test.ts
  yarn-project/circuits.js/src/structs/shared_mutable/scheduled_value_change.ts
  yarn-project/circuits.js/src/structs/shared_mutable/shared_mutable_values.test.ts
  yarn-project/circuits.js/src/structs/shared_mutable/shared_mutable_values.ts
  yarn-project/circuits.js/src/structs/shared_mutable/shared_mutable_values_with_hash.ts
  yarn-project/constants/package.json
  yarn-project/constants/src/constants.gen.ts
  yarn-project/constants/src/scripts/constants.in.ts
  yarn-project/end-to-end/src/e2e_contract_updates.test.ts
  yarn-project/noir-protocol-circuits-types/src/conversion/client.ts
  yarn-project/pxe/src/kernel_oracle/index.ts
  yarn-project/simulator/src/avm/journal/journal.ts
  yarn-project/simulator/src/client/private_execution.ts
Labels: e2e-all

#12087 refactor: replace kv-store backend in pxe, key store and wallet
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_store.test.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/queries.cpp
  yarn-project/aztec/src/bin/index.ts
  yarn-project/cli-wallet/src/bin/index.ts
  yarn-project/cli-wallet/src/cmds/index.ts
  yarn-project/cli-wallet/src/storage/wallet_db.ts
  yarn-project/cli-wallet/src/utils/accounts.ts
  yarn-project/key-store/src/key_store.test.ts
  yarn-project/kv-store/src/lmdb-v2/array.test.ts
  yarn-project/kv-store/src/lmdb-v2/array.ts
  yarn-project/kv-store/src/lmdb-v2/store.ts
  yarn-project/p2p/src/services/data_store.test.ts
  yarn-project/pxe/src/database/kv_pxe_database.test.ts
  yarn-project/pxe/src/database/kv_pxe_database.ts
  yarn-project/pxe/src/pxe_service/test/pxe_service.test.ts
  yarn-project/pxe/src/simulator_oracle/simulator_oracle.test.ts
  yarn-project/pxe/src/synchronizer/synchronizer.test.ts
  yarn-project/pxe/src/utils/create_pxe_service.ts
  yarn-project/txe/src/txe_service/txe_service.ts
Labels: e2e-all, network-all

#12037 chore(ci3): refactor ci3.yml, fix external PR flow
  .github/workflows/ci3.yml
  .vscode/settings.json
  README.md
  bootstrap.sh
  yarn-project/simulator/README.md
Labels: e2e-all, arm64-ci

#12122 feat: partial note handling in aztec-nr
  noir-projects/aztec-nr/aztec/src/discovery/mod.nr
  noir-projects/aztec-nr/aztec/src/discovery/nonce_discovery.nr
  noir-projects/aztec-nr/aztec/src/discovery/partial_notes.nr
  noir-projects/aztec-nr/aztec/src/discovery/private_logs.nr
  noir-projects/aztec-nr/aztec/src/lib.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/utils.nr
  noir-projects/aztec-nr/aztec/src/macros/mod.nr
  noir-projects/aztec-nr/aztec/src/note/discovery/mod.nr
  noir-projects/aztec-nr/aztec/src/note/mod.nr
  noir-projects/aztec-nr/aztec/src/note/note_interface.nr
  noir-projects/aztec-nr/aztec/src/note/utils.nr
  noir-projects/aztec-nr/aztec/src/oracle/note_discovery.nr
  noir-projects/aztec-nr/aztec/src/oracle/notes.nr
  noir-projects/aztec-nr/aztec/src/utils/array/append.nr
  noir-projects/aztec-nr/aztec/src/utils/array/mod.nr
  noir-projects/aztec-nr/aztec/src/utils/array/subbvec.nr
  noir-projects/noir-contracts/contracts/counter_contract/src/main.nr
  yarn-project/circuits.js/package.json
  yarn-project/circuits.js/src/structs/logs/index.ts
  yarn-project/circuits.js/src/structs/logs/log_with_tx_data.ts
  yarn-project/pxe/src/simulator_oracle/index.ts
  yarn-project/simulator/src/acvm/deserialize.ts
  yarn-project/simulator/src/acvm/oracle/oracle.ts
  yarn-project/simulator/src/acvm/oracle/typed_oracle.ts
  yarn-project/simulator/src/acvm/serialize.ts
  yarn-project/simulator/src/client/client_execution_context.ts
  yarn-project/simulator/src/client/db_oracle.ts
  yarn-project/simulator/src/client/private_execution.test.ts
  yarn-project/simulator/src/client/simulator.test.ts
  yarn-project/simulator/src/client/simulator.ts
  yarn-project/simulator/src/client/unconstrained_execution.test.ts
  yarn-project/simulator/src/client/view_data_oracle.ts
  yarn-project/txe/src/oracle/txe_oracle.ts
Labels: e2e-all

#12165 chore(spartan): workaround bot + transfer test conflict
  spartan/bootstrap.sh
Labels: e2e-all

#12128 fix(p2p): prune duplicate peers
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
Labels: ci-external

#12096 fix: Fix epoch monitoring and related e2e tests
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/circuit-types/src/epoch-helpers/index.ts
  yarn-project/circuit-types/src/interfaces/aztec-node.test.ts
  yarn-project/circuit-types/src/interfaces/aztec-node.ts
  yarn-project/circuit-types/src/interfaces/prover-client.ts
  yarn-project/circuit-types/src/interfaces/world_state.ts
  yarn-project/circuit-types/src/l2_block_downloader/l2_block_stream.ts
  yarn-project/circuits.js/src/structs/block_header.ts
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/src/e2e_epochs.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_empty_blocks.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_multi_proof.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_proof_fails.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_test.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/ethereum/src/contracts/rollup.ts
  yarn-project/foundation/src/log/pino-logger.ts
  yarn-project/prover-node/src/factory.ts
  yarn-project/prover-node/src/monitors/epoch-monitor.test.ts
  yarn-project/prover-node/src/monitors/epoch-monitor.ts
  yarn-project/prover-node/src/prover-node.test.ts
  yarn-project/prover-node/src/prover-node.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.test.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/txe/src/node/txe_node.ts
  yarn-project/world-state/src/synchronizer/server_world_state_synchronizer.test.ts
  yarn-project/world-state/src/synchronizer/server_world_state_synchronizer.ts
Labels: e2e-all

#11955 feat: AVM uses native checkpointing trees instead of TS ephemeral forest
  yarn-project/circuit-types/src/interfaces/merkle_tree_operations.ts
  yarn-project/circuit-types/src/tx/validator/tx_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/double_spend_validator.test.ts
  yarn-project/p2p/src/msg_validators/tx_validator/double_spend_validator.ts
  yarn-project/simulator/src/avm/avm_context.test.ts
  yarn-project/simulator/src/avm/avm_context.ts
  yarn-project/simulator/src/avm/avm_simulator.test.ts
  yarn-project/simulator/src/avm/avm_tree.test.ts
  yarn-project/simulator/src/avm/avm_tree.ts
  yarn-project/simulator/src/avm/fixtures/avm_simulation_tester.ts
  yarn-project/simulator/src/avm/fixtures/index.ts
  yarn-project/simulator/src/avm/index.ts
  yarn-project/simulator/src/avm/journal/journal.test.ts
  yarn-project/simulator/src/avm/journal/journal.ts
  yarn-project/simulator/src/avm/journal/nullifiers.test.ts
  yarn-project/simulator/src/avm/journal/nullifiers.ts
  yarn-project/simulator/src/avm/journal/public_storage.ts
  yarn-project/simulator/src/avm/opcodes/external_calls.ts
  yarn-project/simulator/src/public/db_interfaces.ts
  yarn-project/simulator/src/public/fixtures/public_tx_simulation_tester.ts
  yarn-project/simulator/src/public/public_db_sources.test.ts
  yarn-project/simulator/src/public/public_db_sources.ts
  yarn-project/simulator/src/public/public_processor.test.ts
  yarn-project/simulator/src/public/public_processor.ts
  yarn-project/simulator/src/public/public_tx_context.ts
  yarn-project/simulator/src/public/public_tx_simulator.test.ts
  yarn-project/simulator/src/public/public_tx_simulator.ts
  yarn-project/txe/src/oracle/txe_oracle.ts
  yarn-project/txe/src/util/txe_world_state_db.ts
  yarn-project/world-state/src/native/fork_checkpoint.ts
  yarn-project/world-state/src/native/index.ts
Labels: e2e-all

#12171 feat!: remove addNote, compute_note_hash_...
  boxes/boxes/react/src/config.ts
  boxes/boxes/vite/src/config.ts
  docs/docs/aztec/concepts/accounts/index.md
  docs/docs/aztec/smart_contracts/functions/function_transforms.md
  docs/docs/developers/guides/smart_contracts/how_to_compile_contract.md
  docs/docs/developers/guides/smart_contracts/writing_contracts/common_patterns/index.md
  docs/docs/developers/guides/smart_contracts/writing_contracts/how_to_emit_event.md
  docs/docs/developers/reference/environment_reference/cli_reference.md
  docs/docs/developers/reference/environment_reference/cli_wallet_reference.md
  docs/docs/developers/tutorials/codealong/contract_tutorials/counter_contract.md
  docs/docs/migration_notes.md
  noir-projects/aztec-nr/aztec/src/discovery/mod.nr
  noir-projects/aztec-nr/aztec/src/discovery/nonce_discovery.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/utils.nr
  noir-projects/aztec-nr/aztec/src/macros/mod.nr
  noir-projects/aztec-nr/aztec/src/note/note_interface.nr
  noir-projects/aztec-nr/aztec/src/note/utils.nr
  noir-projects/aztec-nr/aztec/src/test/helpers/test_environment.nr
  noir-projects/noir-contracts/contracts/test_contract/src/main.nr
  noir-projects/noir-contracts/contracts/token_blacklist_contract/src/main.nr
  noir-projects/noir-protocol-circuits/crates/types/src/meta/mod.nr
  playground/src/components/contract/contract.tsx
  yarn-project/aztec.js/src/wallet/base_wallet.ts
  yarn-project/circuit-types/src/interfaces/pxe.test.ts
  yarn-project/circuit-types/src/interfaces/pxe.ts
  yarn-project/circuits.js/src/hash/hash.ts
  yarn-project/cli-wallet/src/cmds/add_note.ts
  yarn-project/cli-wallet/src/cmds/index.ts
  yarn-project/cli/src/cmds/contracts/inspect_contract.ts
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/scripts/e2e_test_config.yml
  yarn-project/end-to-end/src/composed/e2e_persistence.test.ts
  yarn-project/end-to-end/src/e2e_blacklist_token_contract/blacklist_token_contract_test.ts
  yarn-project/end-to-end/src/e2e_blacklist_token_contract/minting.test.ts
  yarn-project/end-to-end/src/e2e_blacklist_token_contract/shielding.test.ts
  yarn-project/end-to-end/src/e2e_non_contract_account.test.ts
  yarn-project/end-to-end/src/e2e_offchain_note_delivery.test.ts
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/pxe/src/simulator_oracle/simulator_oracle.test.ts
  yarn-project/simulator/src/client/private_execution.test.ts
  yarn-project/simulator/src/client/simulator.test.ts
  yarn-project/simulator/src/client/simulator.ts
Labels: e2e-all

#12203 fix(p2p): add block proposal topic scoring
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-external

#12205 feat: add wasm memory benchmark to bench.json (redo)
  barretenberg/.gitignore
  barretenberg/acir_tests/.gitignore
  barretenberg/acir_tests/bench_acir_tests.sh
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/bootstrap.sh
  barretenberg/cpp/Earthfile
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/scripts/ci/combine_benchmarks.py
  barretenberg/scripts/combine_benchmarks.py
  barretenberg/ts/bootstrap.sh
  bootstrap.sh
Labels: e2e-all

#12209 fix: P2P messages are propagated
  cspell.json
  yarn-project/p2p/package.json
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/validator-client/src/validator.ts
Labels: e2e-all, network-all

#12297 fix(e2e): p2p_reqresp
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_p2p/reqresp.test.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: ci-full

#12307 fix: run arm64 on master
  .github/workflows/ci3.yml
Labels: arm64-ci

#12331 fix: yoinked from 02-19-kind_upgrade_test
  .github/workflows/ci3.yml
  ci3/run_test_cmd
  spartan/bootstrap.sh
  spartan/scripts/test_kind.sh
Labels: ci-full

#12154 feat: Cycle Group Fuzzer
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group_ultra.fuzzer.cpp
Labels: product-security

#12354 chore: move the validator key index start to 2000
  spartan/aztec-network/values.yaml
  yarn-project/end-to-end/src/spartan/upgrade_rollup_version.test.ts
Labels: ci-full

#12348 refactor: make args simpler to read
  l1-contracts/src/core/Rollup.sol
  l1-contracts/src/core/interfaces/IRollup.sol
  l1-contracts/src/core/libraries/Converter.sol
  l1-contracts/src/core/libraries/RollupLibs/EpochProofLib.sol
  l1-contracts/src/core/libraries/RollupLibs/ExtRollupLib.sol
  l1-contracts/test/Rollup.t.sol
  l1-contracts/test/base/RollupBase.sol
  l1-contracts/test/fees/FeeRollup.t.sol
  yarn-project/archiver/src/archiver/data_retrieval.ts
  yarn-project/ethereum/src/contracts/rollup.ts
  yarn-project/prover-node/src/prover-node-publisher.ts
Labels: ci-full

#12379 chore: Increase timeout for prover full
  yarn-project/end-to-end/bootstrap.sh
Labels: ci-full
