Repository AztecProtocol/aztec-packages, pull requests merged in 2025-10, with the labels that each got.

#17405 chore(docs): Update the glossary
  docs/docs/developers/docs/reference/glossary.md
  docs/docusaurus.config.js
Labels: ci-external

#17413 feat: support using existing ERC20 token for fee and staking
  yarn-project/cli/src/cmds/l1/deploy_l1_contracts.ts
  yarn-project/cli/src/cmds/l1/index.ts
  yarn-project/cli/src/utils/aztec.ts
  yarn-project/ethereum/src/deploy_l1_contracts.test.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
Labels: backport-to-v2

#17335 feat: add flushing rewarder
  l1-contracts/src/core/interfaces/IRollup.sol
  l1-contracts/src/periphery/FlushRewarder.sol
  l1-contracts/src/periphery/interfaces/IFlushRewarder.sol
  l1-contracts/test/staking/rewarded-flushing/rewardedFlushing.t.sol
Labels: backport-to-v2

#17342 feat(avm)!: Handle Empty Calldata
  barretenberg/cpp/pil/vm2/calldata.pil
  barretenberg/cpp/pil/vm2/calldata_hashing.pil
  barretenberg/cpp/src/barretenberg/vm2/constraining/relations/calldata_hashing.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/relations/data_copy.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/relations/tx.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/gadgets/calldata_hashing.cpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/gadgets/calldata_hashing.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/calldata_trace.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/calldata_trace.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/data_copy_trace.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/execution_trace.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/tx_trace.test.cpp
  noir-projects/aztec-nr/aztec/src/hash.nr
  yarn-project/stdlib/src/hash/hash.ts
Labels: ci-full

#17425 fix: improve libp2p connection limits for network discovery
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-external, backport-to-v2

#17436 fix: use archiveAt(0) instead of getBlock to get genesis archive tree root
  yarn-project/ethereum/src/contracts/rollup.ts
Labels: backport-to-v2

#17390 chore: refactored the IPA tests, as part of the IPA audit
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/ipa_recursive.test.cpp
Labels: ci-full, bberg-int-audit

#17403 fix: only "known" errors should be caught during public tx simulation
  yarn-project/simulator/src/public/avm/avm_simulator.test.ts
  yarn-project/simulator/src/public/avm/avm_simulator.ts
  yarn-project/simulator/src/public/avm/errors.ts
  yarn-project/simulator/src/public/avm/opcodes/accrued_substate.ts
  yarn-project/simulator/src/public/avm/opcodes/addressing_mode.ts
  yarn-project/simulator/src/public/avm/opcodes/ec_add.test.ts
  yarn-project/simulator/src/public/avm/opcodes/ec_add.ts
  yarn-project/simulator/src/public/avm/opcodes/environment_getters.ts
  yarn-project/simulator/src/public/avm/opcodes/instruction.ts
  yarn-project/simulator/src/public/bytecode_errors.ts
  yarn-project/simulator/src/public/public_errors.ts
  yarn-project/simulator/src/public/public_processor/public_processor.test.ts
  yarn-project/simulator/src/public/public_tx_simulator/measured_public_tx_simulator.ts
  yarn-project/simulator/src/public/public_tx_simulator/public_tx_simulator.test.ts
  yarn-project/simulator/src/public/public_tx_simulator/public_tx_simulator.ts
  yarn-project/simulator/src/public/side_effect_errors.ts
  yarn-project/simulator/src/public/side_effect_trace.test.ts
  yarn-project/simulator/src/public/side_effect_trace.ts
  yarn-project/simulator/src/public/state_manager/nullifiers.ts
  yarn-project/simulator/src/public/state_manager/state_manager.ts
Labels: ci-full, backport-to-v2

#17469 fix: PublicProcessor recognizes AssertionError messages like regular Error messages
  yarn-project/simulator/src/public/public_processor/public_processor.test.ts
  yarn-project/simulator/src/public/public_processor/public_processor.ts
Labels: ci-full

#17411 fix!: tx trace should handle reverts early in phase followed by skipped items
  barretenberg/cpp/pil/vm2/tx.pil
  barretenberg/cpp/src/barretenberg/vm2/generated/relations/tx.hpp
  barretenberg/cpp/src/barretenberg/vm2/generated/relations/tx_impl.hpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/events/tx_events.hpp
  barretenberg/cpp/src/barretenberg/vm2/simulation/gadgets/tx_execution.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/tx_trace.cpp
  barretenberg/cpp/src/barretenberg/vm2/tracegen/tx_trace.test.cpp
  yarn-project/bb-prover/src/avm_proving_tests/avm_check_circuit3.test.ts
Labels: ci-full

#17422 feat!: entrypoint cleanup
  boxes/boxes/vanilla/app/embedded-wallet.ts
  noir-projects/aztec-nr/aztec/src/authwit/account.nr
  noir-projects/noir-contracts/contracts/account/ecdsa_k_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/ecdsa_r_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/schnorr_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/schnorr_hardcoded_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/schnorr_single_key_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/simulated_account_contract/src/main.nr
  playground/src/components/common/FeePaymentSelector.tsx
  playground/src/components/contract/components/ConfigureInteractionDialog.tsx
  playground/src/components/contract/components/CreateAuthwitDialog.tsx
  playground/src/components/contract/components/CreateContractDialog.tsx
  playground/src/components/contract/components/FunctionCard.tsx
  playground/src/components/navbar/components/WalletHub.tsx
  playground/src/hooks/useTransaction.tsx
  playground/src/wallet/components/CreateAccountDialog.tsx
  playground/src/wallet/embedded_wallet.ts
  yarn-project/accounts/src/defaults/account_contract.ts
  yarn-project/accounts/src/defaults/account_interface.ts
  yarn-project/aztec.js/src/account/account.ts
  yarn-project/aztec.js/src/account/account_contract.ts
  yarn-project/aztec.js/src/account/signerless_account.ts
  yarn-project/aztec.js/src/api/account.ts
  yarn-project/aztec.js/src/api/contract.ts
  yarn-project/aztec.js/src/api/fee.ts
  yarn-project/aztec.js/src/api/wallet.ts
  yarn-project/aztec.js/src/contract/base_contract_interaction.ts
  yarn-project/aztec.js/src/contract/batch_call.ts
  yarn-project/aztec.js/src/contract/contract_function_interaction.ts
  yarn-project/aztec.js/src/contract/deploy_method.ts
  yarn-project/aztec.js/src/contract/interaction_options.ts
  yarn-project/aztec.js/src/fee/fee_juice_payment_method.ts
  yarn-project/aztec.js/src/fee/fee_juice_payment_method_with_claim.ts
  yarn-project/aztec.js/src/fee/fee_payment_method.ts
  yarn-project/aztec.js/src/fee/private_fee_payment_method.ts
  yarn-project/aztec.js/src/fee/public_fee_payment_method.ts
  yarn-project/aztec.js/src/fee/sponsored_fee_payment.ts
  yarn-project/aztec.js/src/utils/authwit.ts
  yarn-project/aztec.js/src/wallet/account_entrypoint_meta_payment_method.ts
  yarn-project/aztec.js/src/wallet/base_wallet.ts
  yarn-project/aztec.js/src/wallet/deploy_account_method.ts
  yarn-project/aztec.js/src/wallet/wallet.ts
  yarn-project/bot/src/base_bot.ts
  yarn-project/cli-wallet/src/cmds/cancel_tx.ts
  yarn-project/cli-wallet/src/cmds/send.ts
  yarn-project/cli-wallet/src/utils/options/fees.ts
  yarn-project/cli-wallet/src/utils/wallet.ts
  yarn-project/end-to-end/src/bench/client_flows/amm.test.ts
  yarn-project/end-to-end/src/bench/client_flows/benchmark.ts
  yarn-project/end-to-end/src/bench/client_flows/bridging.test.ts
  yarn-project/end-to-end/src/bench/client_flows/client_flows_benchmark.ts
  yarn-project/end-to-end/src/bench/client_flows/deployments.test.ts
  yarn-project/end-to-end/src/bench/client_flows/transfers.test.ts
  yarn-project/end-to-end/src/e2e_fees/gas_estimation.test.ts
  yarn-project/end-to-end/src/spartan/setup_test_wallets.ts
  yarn-project/entrypoints/src/account_entrypoint.ts
  yarn-project/entrypoints/src/default_entrypoint.ts
  yarn-project/entrypoints/src/interfaces.ts
  yarn-project/test-wallet/src/wallet/test_wallet.ts
Labels: ci-no-fail-fast

#17484 chore: revert minConnections to 0
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: backport-to-v2

#17483 feat(no-docker-devex/1): Add nested parallel_for support
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_ultra_honk.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/acir_bincode_mocks.hpp
  barretenberg/cpp/src/barretenberg/common/parallel_for_mutex_pool.cpp
  barretenberg/cpp/src/barretenberg/common/thread.cpp
  barretenberg/cpp/src/barretenberg/common/thread.hpp
  barretenberg/cpp/src/barretenberg/common/thread.test.cpp
  barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.test.cpp
  barretenberg/cpp/src/barretenberg/env/hardware_concurrency.cpp
  barretenberg/cpp/src/barretenberg/env/logstr.cpp
  barretenberg/cpp/src/barretenberg/srs/factories/native_crs_factory.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/plookup_tables/plookup_tables.cpp
Labels: ci-full

#17487 feat(no-docker-devex/3): Replace popen with C++ utilities
  barretenberg/cpp/CMakeLists.txt
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/cmake/arch.cmake
  barretenberg/cpp/cmake/libdeflate.cmake
  barretenberg/cpp/cmake/lmdb.cmake
  barretenberg/cpp/cmake/nlohmann_json.cmake
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/api/acir_format_getters.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/exec_pipe.hpp
  barretenberg/cpp/src/barretenberg/api/get_bytecode.hpp
  barretenberg/cpp/src/barretenberg/common/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/common/base64.cpp
  barretenberg/cpp/src/barretenberg/common/base64.hpp
  barretenberg/cpp/src/barretenberg/common/get_bytecode.cpp
  barretenberg/cpp/src/barretenberg/common/get_bytecode.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_integration.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_to_constraint_buf.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_environment.test.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_store.test.cpp
Labels: ci-full

#17529 chore: remove OLD _API CLI, fix build
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/api/aztec_process.cpp
  barretenberg/cpp/src/barretenberg/api/aztec_process.hpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  barretenberg/docs/versioned_docs/version-v0.87.0/bb-cli-reference.md
Labels: ci-full
