Repository AztecProtocol/aztec-packages, pull requests merged in 2025-07, with the labels that each got.

#15443 chore: unrevert stdlib proof
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/boomerang_value_detection/graph_description_ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/ipa_recursive.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/proof_surgeon.hpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.cpp
  barretenberg/cpp/src/barretenberg/goblin/goblin.hpp
  barretenberg/cpp/src/barretenberg/honk/proof_system/types/proof.hpp
  barretenberg/cpp/src/barretenberg/stdlib/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/stdlib/client_ivc_verifier/client_ivc_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/merge_verifier/merge_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/merge_verifier/merge_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/merge_verifier/merge_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/proof/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/stdlib/proof/proof.hpp
  barretenberg/cpp/src/barretenberg/stdlib/proof/proof.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/transcript/transcript.hpp
  barretenberg/cpp/src/barretenberg/stdlib/transcript/transcript.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/transcript/transcript.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.test.cpp
Labels: ci-full

#15439 fix: add serialqueue to idb
  yarn-project/kv-store/package.json
  yarn-project/kv-store/package.local.json
  yarn-project/kv-store/src/indexeddb/store.ts
Labels: backport-to-staging

#15448 chore: fix avm build
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
Labels: ci-full

#15441 chore: Reset block interval when warping to a future slot
  yarn-project/aztec.js/src/test/anvil_test_watcher.ts
  yarn-project/aztec.js/src/test/rollup_cheat_codes.ts
  yarn-project/cli/src/cmds/l1/update_l1_validators.ts
  yarn-project/end-to-end/src/composed/integration_l1_publisher.test.ts
  yarn-project/end-to-end/src/e2e_p2p/upgrade_governance_proposer.test.ts
  yarn-project/end-to-end/src/e2e_sequencer/gov_proposal.test.ts
  yarn-project/end-to-end/src/e2e_synching.test.ts
  yarn-project/end-to-end/src/fixtures/snapshot_manager.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
Labels: ci-no-fail-fast

#15453 fix: readd senders on wallet change
  playground/src/components/sidebar/components/AccountSelector.tsx
Labels: backport-to-staging

#15444 chore: recursive verifiers take stdlib proofs
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
  barretenberg/cpp/src/barretenberg/stdlib/client_ivc_verifier/client_ivc_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/client_ivc_verifier/client_ivc_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/client_ivc_verifier/client_ivc_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/goblin_verifier/goblin_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.hpp
Labels: ci-full

#15467 chore: Configuration for adversarial testnet
  l1-contracts/src/governance/Governance.sol
  l1-contracts/test/builder/GseBuilder.sol
  l1-contracts/test/builder/RollupBuilder.sol
  l1-contracts/test/governance/governance/base.t.sol
  l1-contracts/test/governance/governance/limitedDeposit.t.sol
  l1-contracts/test/harnesses/TestConstants.sol
  yarn-project/aztec/src/bin/index.ts
  yarn-project/aztec/src/cli/chain_l2_config.ts
  yarn-project/ethereum/src/config.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
  yarn-project/foundation/src/config/index.ts
  yarn-project/foundation/src/config/network_name.ts
Labels: backport-to-staging

#15511 chore: added cache to vks
  aztec-nargo/compile_then_postprocess.sh
Labels: backport-to-staging

#15539 chore: call flushEntryQueue from staking asset handler
  l1-contracts/src/mock/StakingAssetHandler.sol
  l1-contracts/test/staking_asset_handler/addValidator.t.sol
  l1-contracts/test/staking_asset_handler/addValidator.tree
  l1-contracts/test/staking_asset_handler/reenterExitedValidator.t.sol
  l1-contracts/test/staking_asset_handler/setWithdrawer.t.sol
Labels: backport-to-staging

#15556 fix: yaml
  spartan/aztec-network/templates/validator.yaml
Labels: backport-to-staging

#15547 chore!: Correct public inputs propagation in the tube
  barretenberg/cpp/src/barretenberg/api/prove_tube.cpp
Labels: ci-full

#15569 fix: Do not delegate vote signature to rpc
  yarn-project/ethereum/src/contracts/empire_base.ts
  yarn-project/ethereum/src/test/start_anvil.ts
  yarn-project/slasher/src/slasher_client.test.ts
Labels: backport-to-staging

#15516 feat!: batch txs in reqresp
  yarn-project/p2p/src/client/interface.ts
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/client/p2p_client.test.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/services/dummy_service.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/reqresp/interface.ts
  yarn-project/p2p/src/services/reqresp/protocols/tx.ts
  yarn-project/p2p/src/services/reqresp/reqresp.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
  yarn-project/p2p/src/services/service.ts
  yarn-project/p2p/src/services/tx_collection/fast_tx_collection.ts
  yarn-project/p2p/src/services/tx_collection/slow_tx_collection.ts
  yarn-project/p2p/src/services/tx_collection/tx_collection.test.ts
  yarn-project/stdlib/src/tx/tx.ts
  yarn-project/stdlib/src/tx/tx_hash.ts
  yarn-project/txe/src/state_machine/dummy_p2p_client.ts
Labels: ci-external

#15598 fix!: aggregate correct nested pairing points in the hiding circuit
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
Labels: ci-full

#15597 fix: use nonce of signing proposer
  yarn-project/ethereum/src/contracts/empire_base.ts
  yarn-project/ethereum/src/contracts/governance_proposer.ts
  yarn-project/ethereum/src/contracts/slashing_proposer.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.test.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.ts
  yarn-project/sequencer-client/src/sequencer/sequencer.ts
  yarn-project/slasher/src/slasher_client.test.ts
Labels: backport-to-staging

#15616 fix: slashing fixes
  yarn-project/ethereum/src/contracts/slashing_proposer.ts
  yarn-project/foundation/src/config/index.ts
  yarn-project/slasher/src/config.ts
  yarn-project/slasher/src/slasher_client.ts
Labels: backport-to-staging

#15591 feat!: VK hash consistency check
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/client_ivc/acir_bincode_mocks.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/native_verification_key.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/stdlib_verification_key.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/oink_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/transcript/transcript.hpp
  yarn-project/stdlib/src/hash/hash.ts
Labels: ci-full

#15643 fix: server pxe pluggable prover
  yarn-project/pxe/src/entrypoints/server/utils.ts
Labels: backport-to-staging

#15567 fix: sed regex for replacing /node/ with /browser/ in import/export statements
  barretenberg/ts/scripts/browser_postprocess.sh
Labels: ci-external

#15528 fix: A lot of fuzzing issues
  barretenberg/cpp/CMakeLists.txt
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/src/barretenberg/circuit_checker/ultra_circuit_checker.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/common/fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_standard.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bool/bool.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bool/bool_standard.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/byte_array/byte_array.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/byte_array/byte_array_standard.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/field/field_standard.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/group/cycle_group.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/safe_uint/safe_uint.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/safe_uint/safe_uint_standard.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/uint/uint.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base_impl.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator.fuzzer.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_mini.fuzzer.cpp
  container-builds/fuzzing-container/src/Dockerfile
  container-builds/fuzzing-container/src/entrypoint.sh
Labels: product-security

#15665 chore!: remove all PublicComponentKeys
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/mock_circuit_producer.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/claim.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format_mocks.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/bigint_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/block_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ec_operations.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ecdsa_secp256k1.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ecdsa_secp256r1.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/honk_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/multi_scalar_mul.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/poseidon2_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/sha256_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/honk/composer/permutation_lib.hpp
  barretenberg/cpp/src/barretenberg/honk/proving_key_inspector.hpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/pairing_points.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/public_input_component/public_input_component.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_key.hpp
  barretenberg/cpp/src/barretenberg/stdlib/special_public_inputs/special_public_inputs.hpp
  barretenberg/cpp/src/barretenberg/stdlib/special_public_inputs/special_public_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base_impl.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_proving_key.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/goblin_avm_recursive_verifier.hpp
  barretenberg/noir/bb_proof_verification/src/lib.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-init/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-inner/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-reset/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-tail-to-public/Prover.toml
  noir-projects/noir-protocol-circuits/crates/private-kernel-tail/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-base-private/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-base-public/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-block-merge/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-block-root/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-merge/Prover.toml
  noir-projects/noir-protocol-circuits/crates/rollup-root/Prover.toml
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
  yarn-project/constants/src/constants.gen.ts
Labels: ci-full

#15583 feat!: BlockTxReqResp
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/mem_pools/attestation_pool/attestation_pool.ts
  yarn-project/p2p/src/mem_pools/attestation_pool/attestation_pool_test_suite.ts
  yarn-project/p2p/src/mem_pools/attestation_pool/kv_attestation_pool.ts
  yarn-project/p2p/src/mem_pools/attestation_pool/memory_attestation_pool.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/reqresp/interface.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/bitvector.test.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/bitvector.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/block_txs.test.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/block_txs_handler.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/block_txs_reqresp.ts
  yarn-project/p2p/src/services/reqresp/protocols/block_txs/index.ts
  yarn-project/p2p/src/services/reqresp/protocols/index.ts
  yarn-project/p2p/src/services/reqresp/rate-limiter/rate_limits.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
  yarn-project/p2p/src/services/reqresp/status.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
Labels: ci-external

#15705 feat!: small improvements for direct peers
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/services/dummy_service.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/peer-manager/interface.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
Labels: ci-external

#15700 chore: optional L1 TX cancellation
  yarn-project/ethereum/package.json
  yarn-project/ethereum/src/l1_tx_utils.test.ts
  yarn-project/ethereum/src/l1_tx_utils.ts
  yarn-project/ethereum/src/l1_tx_utils_with_blobs.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/yarn.lock
Labels: backport-to-staging

#15710 chore: move verifier input mocking to designated files
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.test.cpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
Labels: ci-full

#15685 chore: enable kernelless simulation in playground
  noir-projects/aztec-nr/aztec/src/macros/aztec.nr
  noir-projects/noir-contracts/contracts/account/simulated_account_contract/src/main.nr
  noir-projects/noir-contracts/contracts/account/simulated_account_contract/src/public_key_note.nr
  noir-projects/noir-contracts/contracts/app/nft_contract/src/main.nr
  noir-projects/noir-contracts/contracts/app/simple_token_contract/src/main.nr
  noir-projects/noir-contracts/contracts/app/token_contract/src/main.nr
  playground/src/components/contract/components/FunctionCard.tsx
  yarn-project/pxe/src/contract_function_simulator/contract_function_simulator.ts
Labels: backport-to-staging

#15702 feat(bbapi): CLI uses bbapi CIVC
  .github/workflows/auto-rebase-pr.yml
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/api/bbapi.hpp
  barretenberg/cpp/src/barretenberg/api/bbapi_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/bbapi_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/api/bbapi_execute.hpp
  barretenberg/cpp/src/barretenberg/api/bbapi_shared.hpp
  barretenberg/cpp/src/barretenberg/api/bbapi_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/bbapi_ultra_honk.hpp
  barretenberg/cpp/src/barretenberg/api/bbrpc_commands.hpp
  barretenberg/cpp/src/barretenberg/api/bbrpc_execute.hpp
  barretenberg/cpp/src/barretenberg/api/write_prover_output.hpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  barretenberg/cpp/src/barretenberg/polynomials/backing_memory.hpp
  bootstrap.sh
  ci3/aws_request_instance
  noir-projects/scripts/generate_vk_json.js
  scripts/auto_rebase_pr.sh
Labels: ci-full

#15731 chore: p2p integration test deflake
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
Labels: ci-external

#15748 fix: use cached VK for public base rollup
  ci.sh
  noir-projects/noir-protocol-circuits/bootstrap.sh
Labels: backport-to-staging

#15758 fix: yarn project cache hash when AVM is disabled
  yarn-project/bootstrap.sh
  yarn-project/end-to-end/bootstrap.sh
Labels: backport-to-staging

#14323 fix: Better handling of maxPeerCount
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-external

#15760 chore: Attempt to deflake preferred peers
  .test_patterns.yml
  yarn-project/end-to-end/src/e2e_p2p/preferred_gossip_network.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: ci-external

#15785 fix: aztec-wallet version
  yarn-project/cli-wallet/src/bin/index.ts
Labels: backport-to-staging

#15789 chore: update config
  spartan/terraform/deploy-telemetry/main.tf
  spartan/terraform/deploy-telemetry/values/public-otel-collector.yaml
  spartan/terraform/gke-cluster/snapshots.tf
  yarn-project/aztec/src/cli/chain_l2_config.ts
Labels: backport-to-staging

#15747 chore!: Remove circuit_size from all VKs
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/dsl/acir_format/avm2_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/mock_verifier_inputs.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/mega_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/ultra_rollup_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/honk/library/grand_product_delta.hpp
  barretenberg/cpp/src/barretenberg/honk/utils/honk_key_gen.hpp
  barretenberg/cpp/src/barretenberg/protogalaxy/protogalaxy_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/oink_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_verification_keys_comparator.hpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_key.hpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_keys.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/witness_computation.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/proving_helper.cpp
Labels: ci-full

#15812 chore: remove unnecessary '== true's
  noir-projects/aztec-nr/aztec/src/authwit/account.nr
  noir-projects/aztec-nr/aztec/src/macros/functions/utils.nr
  noir-projects/noir-contracts/contracts/app/nft_contract/src/test/access_control.nr
  noir-projects/noir-contracts/contracts/app/orderbook_contract/src/order.nr
  noir-projects/noir-contracts/contracts/app/token_contract/src/test/access_control.nr
Labels: ci-external

#15826 feat!: disconnect from peers on heartbeat
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
Labels: ci-external

#15796 chore: break p2p_client.integration into smaller test files
  .test_patterns.yml
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_block_txs.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_message_propagation.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_status_handshake.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_txs.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: ci-external

#15663 fix: resolve DinD dns namespace resolution
  spartan/bootstrap.sh
  spartan/quickstart.md
  spartan/scripts/patch_dns.sh
Labels: ci-external

#15773 chore: k8 high tps transaction dropping test
  spartan/aztec-network/templates/validator.yaml
  spartan/aztec-network/values/ci-tx-drop.yaml
  spartan/bootstrap.sh
  yarn-project/end-to-end/src/spartan/n_tps.test.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
Labels: ci-external

#15854 chore(docs): add 'ci' command to bootstrap script for building and testing documentation
  docs/bootstrap.sh
Labels: backport-to-master

#15715 fix: use non-empty block in benchmarking to include outhash
  l1-contracts/test/benchmark/happy.t.sol
Labels: ci-external

#15904 fix: check fallback env vars
  yarn-project/aztec/src/cli/aztec_start_options.ts
  yarn-project/aztec/src/cli/util.ts
Labels: backport-to-master

#15920 fix: Propose before voting in multicall
  .test_patterns.yml
  yarn-project/end-to-end/src/e2e_sequencer/gov_proposal.test.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/ethereum/src/test/start_anvil.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.test.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.ts
  yarn-project/validator-client/src/validator.ts
Labels: backport-to-master, ci-no-fail-fast

#15929 chore!: update Aztec structured trace sizes
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/honk/execution_trace/mega_execution_trace.hpp
Labels: ci-full

#15704 feat: hiding circuit in noir
  barretenberg/cpp/CMakePresets.json
  barretenberg/cpp/scripts/benchmark_example_ivc_flow_remote.sh
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_to_constraint_buf.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/blake3_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/recursion_constraint.hpp
  barretenberg/cpp/src/barretenberg/polynomials/serialize.hpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/recursive_decider_verification_key.hpp
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
Labels: ci-full

#15777 feat(bbapi): CIVC end to end
  barretenberg/acir_tests/browser-test-app/src/index.ts
  barretenberg/cpp/src/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/api/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/api/api_client_ivc.test.cpp
  barretenberg/cpp/src/barretenberg/api/api_msgpack.hpp
  barretenberg/cpp/src/barretenberg/api/bbapi_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  barretenberg/cpp/src/barretenberg/bbapi/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/bbapi/bbapi.hpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi.test.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_client_ivc.hpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_execute.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_execute.hpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_shared.hpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/bbapi/bbapi_ultra_honk.hpp
  barretenberg/cpp/src/barretenberg/bbapi/c_bind.cpp
  barretenberg/cpp/src/barretenberg/bbapi/c_bind.hpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/common/msgpack_to_json.cpp
  barretenberg/cpp/src/barretenberg/common/msgpack_to_json.hpp
  barretenberg/cpp/src/barretenberg/common/named_union.hpp
  barretenberg/cpp/src/barretenberg/common/throw_or_abort.hpp
  barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.cpp
  barretenberg/cpp/src/barretenberg/env/throw_or_abort_impl.cpp
  barretenberg/cpp/src/barretenberg/env/throw_or_abort_impl.hpp
  barretenberg/cpp/src/barretenberg/goblin/types.hpp
  barretenberg/cpp/src/barretenberg/honk/execution_trace/execution_trace_usage_tracker.hpp
  barretenberg/cpp/src/barretenberg/honk/proof_system/types/proof.hpp
  barretenberg/cpp/src/barretenberg/serialize/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/serialize/msgpack_impl.hpp
  barretenberg/cpp/src/barretenberg/serialize/msgpack_impl/check_memory_span.hpp
  barretenberg/cpp/src/barretenberg/serialize/msgpack_impl/func_traits.hpp
  barretenberg/cpp/src/barretenberg/serialize/msgpack_impl/schema_name.hpp
  barretenberg/ts/.gitignore
  barretenberg/ts/bootstrap.sh
  barretenberg/ts/package.json
  barretenberg/ts/src/barretenberg/backend.ts
  barretenberg/ts/src/barretenberg/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_base/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/index.ts
  barretenberg/ts/src/cbind/README.md
  barretenberg/ts/src/cbind/generate.ts
  barretenberg/ts/src/cbind/schema_compiler.ts
  barretenberg/ts/yarn.lock
Labels: ci-full

#15915 feat: Fuzzers for in-circuit hash implementations (sha256, keccak, blake2s, blake3s)
  barretenberg/cpp/src/barretenberg/stdlib/hash/blake2s/blake2s.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/blake3s/blake3s.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/keccak/keccak.fuzzer.cpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/sha256/sha256.fuzzer.cpp
Labels: product-security

#15987 fix: throw when making Fr from negatives
  yarn-project/foundation/src/fields/fields.ts
Labels: backport-to-master

#15953 chore: replace q_arith with q_3 in memory relation
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/boomerang_value_detection/graph.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_contract.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/honk_zk_contract.hpp
  barretenberg/cpp/src/barretenberg/relations/memory_relation.hpp
  barretenberg/cpp/src/barretenberg/relations/ultra_relation_consistency.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
  barretenberg/sol/src/honk/Relations.sol
Labels: ci-full

#16012 fix: Rollback state on failed tx processing
  barretenberg/cpp/src/barretenberg/vm2/testing/avm_inputs.testdata.bin
  yarn-project/end-to-end/src/e2e_block_building.test.ts
  yarn-project/prover-client/src/block-factory/light.ts
  yarn-project/sequencer-client/src/sequencer/block_builder.test.ts
  yarn-project/simulator/package.json
  yarn-project/simulator/src/public/public_processor/public_processor.test.ts
  yarn-project/simulator/src/public/public_processor/public_processor.ts
  yarn-project/stdlib/src/tests/factories.ts
  yarn-project/stdlib/src/tx/__snapshots__/block_header.test.ts.snap
  yarn-project/stdlib/src/tx/state_reference.ts
Labels: ci-no-fail-fast

#15813 feat: Delayed signature verification during block proposals
  l1-contracts/src/core/Rollup.sol
  l1-contracts/src/core/RollupCore.sol
  l1-contracts/src/core/interfaces/IRollup.sol
  l1-contracts/src/core/libraries/Errors.sol
  l1-contracts/src/core/libraries/compressed-data/BlockLog.sol
  l1-contracts/src/core/libraries/rollup/EpochProofLib.sol
  l1-contracts/src/core/libraries/rollup/ExtRollupLib.sol
  l1-contracts/src/core/libraries/rollup/ExtRollupLib2.sol
  l1-contracts/src/core/libraries/rollup/ExtRollupLib3.sol
  l1-contracts/src/core/libraries/rollup/InvalidateLib.sol
  l1-contracts/src/core/libraries/rollup/ProposeLib.sol
  l1-contracts/src/core/libraries/rollup/STFLib.sol
  l1-contracts/src/core/libraries/rollup/StakingLib.sol
  l1-contracts/src/core/libraries/rollup/ValidatorSelectionLib.sol
  l1-contracts/src/mock/StakingAssetHandler.sol
  l1-contracts/src/shared/libraries/SignatureLib.sol
  l1-contracts/test/Rollup.t.sol
  l1-contracts/test/RollupGetters.t.sol
  l1-contracts/test/base/RollupBase.sol
  l1-contracts/test/benchmark/happy.t.sol
  l1-contracts/test/compression/PreHeating.t.sol
  l1-contracts/test/fees/FeeRollup.t.sol
  l1-contracts/test/fees/MinimalFeeModel.sol
  l1-contracts/test/validator-selection/ValidatorSelection.t.sol
  l1-contracts/test/validator-selection/ValidatorSelectionBase.sol
  yarn-project/archiver/src/archiver/archiver.test.ts
  yarn-project/archiver/src/archiver/data_retrieval.ts
  yarn-project/cli/src/cmds/devnet/bootstrap_network.ts
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/fixtures/snapshot_manager.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/end-to-end/src/integration/integration_l1_publisher.test.ts
  yarn-project/ethereum/src/contracts/rollup.ts
  yarn-project/ethereum/src/deploy_l1_contracts.ts
  yarn-project/ethereum/src/index.ts
  yarn-project/ethereum/src/l1_artifacts.ts
  yarn-project/l1-artifacts/scripts/generate-artifacts.sh
  yarn-project/prover-node/src/job/epoch-proving-job-data.test.ts
  yarn-project/prover-node/src/job/epoch-proving-job-data.ts
  yarn-project/prover-node/src/job/epoch-proving-job.test.ts
  yarn-project/prover-node/src/job/epoch-proving-job.ts
  yarn-project/prover-node/src/prover-node-publisher.test.ts
  yarn-project/prover-node/src/prover-node-publisher.ts
  yarn-project/prover-node/src/prover-node.test.ts
  yarn-project/prover-node/src/prover-node.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.test.ts
  yarn-project/sequencer-client/src/publisher/sequencer-publisher.ts
  yarn-project/stdlib/src/block/proposal/committee_attestation.ts
Labels: ci-no-fail-fast

#16071 chore: Revert upgraded libp2p (#15911)"
  .test_patterns.yml
  yarn-project/cli/package.json
  yarn-project/cli/src/cmds/misc/generate_bootnode_enr.ts
  yarn-project/cli/src/cmds/misc/generate_p2p_private_key.ts
  yarn-project/cli/src/cmds/misc/index.ts
  yarn-project/end-to-end/src/e2e_p2p/p2p_network.ts
  yarn-project/end-to-end/src/e2e_p2p/preferred_gossip_network.test.ts
  yarn-project/foundation/package.json
  yarn-project/foundation/src/log/libp2p_logger.ts
  yarn-project/p2p/package.json
  yarn-project/p2p/src/bootstrap/bootstrap.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_message_propagation.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_status_handshake.test.ts
  yarn-project/p2p/src/client/test/p2p_client.integration_txs.test.ts
  yarn-project/p2p/src/enr/generate-enr.ts
  yarn-project/p2p/src/index.ts
  yarn-project/p2p/src/services/discv5/discV5_service.ts
  yarn-project/p2p/src/services/discv5/discv5_service.test.ts
  yarn-project/p2p/src/services/dummy_service.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/peer-manager/interface.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/batch_connection_sampler.test.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.test.ts
  yarn-project/p2p/src/test-helpers/generate-peer-id-private-keys.ts
  yarn-project/p2p/src/test-helpers/make-enrs.ts
  yarn-project/p2p/src/test-helpers/make-test-p2p-clients.ts
  yarn-project/p2p/src/test-helpers/mock-pubsub.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/p2p/src/testbench/worker_client_manager.ts
  yarn-project/p2p/src/util.test.ts
  yarn-project/p2p/src/util.ts
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/yarn.lock
Labels: ci-external

#16130 fix: Updated req/resp timeouts
  yarn-project/p2p/src/services/reqresp/config.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: backport-to-master

#16134 chore: update default signal pct
  yarn-project/aztec/src/cli/chain_l2_config.ts
Labels: backport-to-master

#15986 chore: add a `PG_TAIL` proof and queue type
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.cpp
  barretenberg/cpp/src/barretenberg/client_ivc/client_ivc.hpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_to_constraint_buf.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/ivc_recursion_constraint.test.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/recursion_constraint.hpp
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/components/previous_kernel_validator.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_inner.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_reset.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_tail.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/private_kernel_tail_to_public.nr
  noir-projects/noir-protocol-circuits/crates/private-kernel-lib/src/tests/previous_kernel_validator_builder/mod.nr
  noir-projects/noir-protocol-circuits/crates/types/src/abis/private_kernel_data.nr
  noir-projects/noir-protocol-circuits/crates/types/src/constants.nr
Labels: ci-full
