Repository AztecProtocol/aztec-packages, pull requests merged in 2025-04, with the labels that each got.

#13061 fix: tagging bug
  yarn-project/end-to-end/src/e2e_event_logs.test.ts
  yarn-project/pxe/src/pxe_oracle_interface/pxe_oracle_interface.test.ts
  yarn-project/pxe/src/pxe_oracle_interface/pxe_oracle_interface.ts
  yarn-project/pxe/src/storage/tagging_data_provider/tagging_data_provider.ts
Labels: ci-full

#13204 chore: Cleanup config vars for alpha-testnet
  docs/docs/run_node/guides/run_nodes/how_to_run_prover_draft.md
  spartan/aztec-network/templates/full-node.yaml
  spartan/aztec-network/templates/prover-node.yaml
  spartan/aztec-network/values.yaml
  spartan/aztec-network/values/alpha-testnet.yaml
  yarn-project/aztec-node/src/sentinel/config.ts
  yarn-project/aztec/terraform/node/main.tf
  yarn-project/aztec/terraform/prover-node/main.tf
  yarn-project/aztec/terraform/prover/main.tf
  yarn-project/end-to-end/src/fixtures/snapshot_manager.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/sequencer-client/src/config.ts
Labels: ci-full

#13277 chore: flake
  .test_patterns.yml
  yarn-project/end-to-end/bootstrap.sh
Labels: ci-full

#13187 chore: nuking debug-only logger and various unused functionality in `foundation`
  yarn-project/foundation/package.json
  yarn-project/foundation/src/index.ts
  yarn-project/foundation/src/log/debug.ts
  yarn-project/foundation/src/log/index.ts
  yarn-project/foundation/src/log/log_history.test.ts
  yarn-project/foundation/src/log/log_history.ts
  yarn-project/foundation/src/log/noir_debug_log_util.ts
  yarn-project/foundation/src/transport/browser/index.ts
  yarn-project/foundation/src/transport/browser/message_port_socket.ts
  yarn-project/foundation/src/transport/browser/shared_worker_connector.ts
  yarn-project/foundation/src/transport/browser/shared_worker_listener.ts
  yarn-project/foundation/src/transport/browser/worker_connector.ts
  yarn-project/foundation/src/transport/browser/worker_listener.ts
  yarn-project/foundation/src/transport/index.ts
  yarn-project/foundation/src/wasm/README.md
  yarn-project/foundation/src/wasm/empty_wasi_sdk.ts
  yarn-project/foundation/src/wasm/fixtures/gcd.wasm
  yarn-project/foundation/src/wasm/fixtures/gcd.wat
  yarn-project/foundation/src/wasm/index.ts
  yarn-project/foundation/src/wasm/wasm_module.ts
  yarn-project/foundation/src/worker/browser/index.ts
  yarn-project/foundation/src/worker/browser/start_web_module.ts
  yarn-project/foundation/src/worker/browser/web_data_store.ts
  yarn-project/foundation/src/worker/browser/web_worker.ts
  yarn-project/foundation/src/worker/data_store.ts
  yarn-project/foundation/src/worker/index.ts
  yarn-project/foundation/src/worker/node/index.ts
  yarn-project/foundation/src/worker/node/node_data_store.ts
  yarn-project/foundation/src/worker/node/node_worker.ts
  yarn-project/foundation/src/worker/node/start_node_module.ts
  yarn-project/foundation/src/worker/wasm_worker.ts
  yarn-project/foundation/src/worker/worker_pool.ts
  yarn-project/pxe/src/storage/capsule_data_provider/capsule_data_provider.ts
Labels: ci-full

#13281 chore: update gov and proposer configs
  l1-contracts/src/governance/Governance.sol
  yarn-project/end-to-end/src/e2e_p2p/upgrade_governance_proposer.test.ts
  yarn-project/ethereum/src/config.ts
Labels: ci-full

#13249 refactor: renaming unconstrained function as utility in TS
  boxes/boxes/react/src/pages/contract.tsx
  boxes/boxes/vite/src/pages/contract.tsx
  noir-projects/aztec-nr/aztec/src/context/utility_context.nr
  playground/src/components/contract/contract.tsx
  yarn-project/archiver/src/archiver/archiver.ts
  yarn-project/archiver/src/archiver/archiver_store.ts
  yarn-project/archiver/src/archiver/archiver_store_test_suite.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/contract_class_store.ts
  yarn-project/archiver/src/archiver/kv_archiver_store/kv_archiver_store.ts
  yarn-project/archiver/src/factory.ts
  yarn-project/aztec.js/src/api/deployment.ts
  yarn-project/aztec.js/src/contract/base_contract_interaction.ts
  yarn-project/aztec.js/src/contract/batch_call.ts
  yarn-project/aztec.js/src/contract/contract.test.ts
  yarn-project/aztec.js/src/contract/contract_function_interaction.ts
  yarn-project/aztec.js/src/deployment/broadcast_function.ts
  yarn-project/aztec.js/src/wallet/account_wallet.ts
  yarn-project/aztec.js/src/wallet/base_wallet.ts
  yarn-project/aztec.js/src/wallet/wallet.ts
  yarn-project/end-to-end/src/e2e_deploy_contract/contract_class_registration.test.ts
  yarn-project/end-to-end/src/e2e_state_vars.test.ts
  yarn-project/protocol-contracts/fixtures/UtilityFunctionBroadcastedEventData.hex
  yarn-project/protocol-contracts/src/class-registerer/__snapshots__/private_function_broadcasted_event.test.ts.snap
  yarn-project/protocol-contracts/src/class-registerer/__snapshots__/utility_function_broadcasted_event.test.ts.snap
  yarn-project/protocol-contracts/src/class-registerer/contract_class_registered_event.ts
  yarn-project/protocol-contracts/src/class-registerer/index.ts
  yarn-project/protocol-contracts/src/class-registerer/lazy.ts
  yarn-project/protocol-contracts/src/class-registerer/private_function_broadcasted_event.ts
  yarn-project/protocol-contracts/src/class-registerer/utility_function_broadcasted_event.test.ts
  yarn-project/protocol-contracts/src/class-registerer/utility_function_broadcasted_event.ts
  yarn-project/protocol-contracts/src/tests/fixtures.ts
  yarn-project/pxe/src/pxe_service/pxe_service.ts
  yarn-project/pxe/src/test/pxe_test_suite.ts
  yarn-project/simulator/src/private/execution_data_provider.ts
  yarn-project/simulator/src/private/index.ts
  yarn-project/simulator/src/private/private_execution_oracle.ts
  yarn-project/simulator/src/private/simulator.ts
  yarn-project/simulator/src/private/utility_execution.test.ts
  yarn-project/simulator/src/private/utility_execution_oracle.ts
  yarn-project/simulator/src/public/avm/fixtures/base_avm_simulation_tester.ts
  yarn-project/stdlib/src/abi/abi.ts
  yarn-project/stdlib/src/abi/contract_artifact.ts
  yarn-project/stdlib/src/contract/artifact_hash.ts
  yarn-project/stdlib/src/contract/index.ts
  yarn-project/stdlib/src/contract/interfaces/contract_class.ts
  yarn-project/stdlib/src/contract/private_function_membership_proof.test.ts
  yarn-project/stdlib/src/contract/private_function_membership_proof.ts
  yarn-project/stdlib/src/contract/unconstrained_function_membership_proof.test.ts
  yarn-project/stdlib/src/contract/utility_function_membership_proof.test.ts
  yarn-project/stdlib/src/contract/utility_function_membership_proof.ts
  yarn-project/stdlib/src/interfaces/archiver.test.ts
  yarn-project/stdlib/src/interfaces/aztec-node.test.ts
  yarn-project/stdlib/src/interfaces/pxe.test.ts
  yarn-project/stdlib/src/interfaces/pxe.ts
  yarn-project/stdlib/src/noir/index.ts
  yarn-project/stdlib/src/tests/factories.ts
  yarn-project/txe/src/util/txe_public_contract_data_source.ts
Labels: ci-full

#13293 chore: bump full prover test to 32 cores. hoping to boost speed.
  yarn-project/end-to-end/bootstrap.sh
Labels: ci-full

#13268 fix: import right assert
  yarn-project/bb-prover/src/prover/bb_prover.ts
Labels: ci-full

#13328 fix: remove second msg discovery call in sync_notes
  noir-projects/aztec-nr/aztec/src/macros/aztec.nr
Labels: ci-full

#13217 feat: Honk will always have pairing point object
  barretenberg/acir_tests/bbjs-test/src/index.ts
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/flows/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/flows/sol_honk.sh
  barretenberg/acir_tests/flows/sol_honk_zk.sh
  barretenberg/acir_tests/sol-test/src/index.js
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_format/acir_format.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/c_bind.cpp
  barretenberg/cpp/src/barretenberg/dsl/acir_proofs/c_bind.hpp
  barretenberg/ts/src/barretenberg/backend.ts
  barretenberg/ts/src/barretenberg_api/index.ts
  barretenberg/ts/src/index.ts
  barretenberg/ts/src/main.ts
  barretenberg/ts/src/proof/index.ts
  noir-projects/scripts/generate_vk_json.js
  yarn-project/noir-bb-bench/src/index.ts
Labels: ci-full

#13348 fix: Warn when inconsistent gas limit
  yarn-project/end-to-end/src/e2e_sequencer_config.test.ts
  yarn-project/sequencer-client/src/client/sequencer-client.ts
Labels: ci-full

#13093 feat: preload CRS files once in GKE
  spartan/aztec-network/templates/prover-agent.yaml
  yarn-project/aztec/src/cli/cli.ts
  yarn-project/aztec/src/cli/preload_crs.ts
Labels: ci-full

#13247 feat: node mempool limiting
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.test.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
  yarn-project/p2p/src/msg_validators/tx_validator/archive_cache.test.ts
  yarn-project/p2p/src/msg_validators/tx_validator/archive_cache.ts
  yarn-project/p2p/src/msg_validators/tx_validator/gas_validator.test.ts
  yarn-project/p2p/src/msg_validators/tx_validator/gas_validator.ts
  yarn-project/p2p/src/msg_validators/tx_validator/index.ts
  yarn-project/sequencer-client/src/tx_validator/tx_validator_factory.ts
  yarn-project/stdlib/src/tests/mocks.ts
  yarn-project/stdlib/src/tx/validator/error_texts.ts
Labels: ci-external

#12946 chore: 1tps kind test + nightly updates
  .test_patterns.yml
  bootstrap.sh
  ci3/bootstrap_ec2
  spartan/aztec-network/templates/blob-sink.yaml
  spartan/aztec-network/values/ci-1tps.yaml
  spartan/bootstrap.sh
  spartan/scripts/deploy_kind.sh
  spartan/scripts/monitor_k8s_deployment.sh
  yarn-project/end-to-end/src/spartan/1tps.test.ts
  yarn-project/end-to-end/src/spartan/setup_test_wallets.ts
  yarn-project/ethereum/src/l1_tx_utils.ts
Labels: ci-full

#13396 chore: Dump container netstat on address in use
  .github/workflows/ci3.yml
  ci.sh
  ci3/bootstrap_ec2
Labels: ci-full

#13475 feat: fast PXE sync
  cspell.json
  yarn-project/pxe/src/synchronizer/synchronizer.ts
  yarn-project/stdlib/src/block/l2_block_stream/l2_block_stream.test.ts
  yarn-project/stdlib/src/block/l2_block_stream/l2_block_stream.ts
Labels: ci-full

#13467 feat(acir_formal_proofs): formal proofs for Noir cast
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/README.md
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/acir_loader.cpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/acir_loader.hpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/acir_loader.test.cpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/formal_proofs.cpp
  barretenberg/cpp/src/barretenberg/acir_formal_proofs/formal_proofs.hpp
Labels: product-security

#13529 fix(p2p): persist p2p private key on rollup address change
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/bootstrap/bootstrap.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/util.test.ts
  yarn-project/p2p/src/util.ts
  yarn-project/p2p/src/utils.test.ts
Labels: ci-external

#12585 feat(p2p): add private peers
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/services/discv5/discV5_service.ts
  yarn-project/p2p/src/services/discv5/discv5_service.test.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.test.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
Labels: ci-external

#13551 feat: SMT verification module updates
  barretenberg/cpp/src/barretenberg/smt_verification/CMakeLists.txt
  barretenberg/cpp/src/barretenberg/smt_verification/README.md
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_schema.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/standard_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/subcircuits.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_examples.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/smt_polynomials.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bvterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffiterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/iterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/util/smt_util.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/circuit_builder_base.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/standard_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
Labels: product-security

#13489 fix: make translator use ultra rather than eccvm ops
  barretenberg/cpp/src/barretenberg/op_queue/ecc_op_queue.hpp
  barretenberg/cpp/src/barretenberg/op_queue/ecc_ops_table.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.test.cpp
Labels: crypto

#13560 fix: pass along coinbase
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/components/block_root_rollup_output_composer.nr
  noir-projects/noir-protocol-circuits/crates/rollup-lib/src/block_root/empty_block_root_rollup_inputs.nr
Labels: ci-full

#13567 fix: Add version to gossipsub protocol
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/test-helpers/make-test-p2p-clients.ts
  yarn-project/stdlib/src/p2p/block_attestation.ts
  yarn-project/stdlib/src/p2p/block_proposal.ts
  yarn-project/stdlib/src/p2p/gossipable.ts
  yarn-project/stdlib/src/p2p/interface.ts
  yarn-project/stdlib/src/p2p/topic_type.ts
  yarn-project/stdlib/src/tx/tx.ts
Labels: ci-full

#13736 refactor: bb.js non-inlined web workers
  barretenberg/acir_tests/browser-test-app/package.json
  barretenberg/acir_tests/browser-test-app/tsconfig.json
  barretenberg/acir_tests/browser-test-app/webpack.config.js
  barretenberg/acir_tests/yarn.lock
  barretenberg/ts/package.json
  barretenberg/ts/src/barretenberg/index.ts
  barretenberg/ts/src/barretenberg_api/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/factory/browser/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/factory/browser/main.worker.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/factory/node/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_thread/factory/browser/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_thread/factory/browser/thread.worker.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_thread/factory/node/index.ts
  barretenberg/ts/src/barretenberg_wasm/helpers/browser/index.ts
  barretenberg/ts/src/barretenberg_wasm/helpers/node/index.ts
  barretenberg/ts/src/barretenberg_wasm/index.test.ts
  barretenberg/ts/src/barretenberg_wasm/index.ts
  barretenberg/ts/src/bindgen/typescript.ts
  barretenberg/ts/src/index.ts
  barretenberg/ts/tsconfig.browser.json
  barretenberg/ts/tsconfig.json
  barretenberg/ts/webpack.config.js
  barretenberg/ts/yarn.lock
  boxes/boxes/react/package.json
  boxes/boxes/react/webpack.config.js
  boxes/boxes/vanilla/package.json
  boxes/boxes/vanilla/webpack.config.js
  boxes/contract-only/package.json
  boxes/yarn.lock
  yarn-project/ivc-integration/package.json
  yarn-project/ivc-integration/webpack.config.js
  yarn-project/noir-bb-bench/package.json
  yarn-project/yarn.lock
Labels: ci-full

#13743 feat: Tighter timing on ACVM
  yarn-project/bb-prover/src/prover/bb_private_kernel_prover.ts
  yarn-project/bb-prover/src/prover/bb_prover.ts
  yarn-project/bb-prover/src/test/test_circuit_prover.ts
  yarn-project/simulator/src/private/providers/acvm_native.ts
  yarn-project/simulator/src/private/providers/acvm_wasm.ts
  yarn-project/simulator/src/private/providers/acvm_wasm_with_blobs.ts
  yarn-project/simulator/src/private/providers/circuit_recording/simulation_provider_recorder_wrapper.ts
  yarn-project/simulator/src/private/providers/simulation_provider.ts
Labels: ci-full

#13488 fix: remove insecure dummy round derivation from sumcheck and shplemini
  barretenberg/cpp/src/barretenberg/commitment_schemes/gemini/gemini.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/ipa/ipa.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/kzg/kzg.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplemini.hpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/shplonk/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes_recursion/shplemini.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm.test.cpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_verifier.cpp
  barretenberg/cpp/src/barretenberg/polynomials/gate_separator.hpp
  barretenberg/cpp/src/barretenberg/polynomials/row_disabling_polynomial.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/decider_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/padding_indicator_array/padding_indicator_array.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/padding_indicator_array/padding_indicator_array.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_zk_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_rollup_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.hpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_round.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/decider_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/sumcheck.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/verifier.cpp
Labels: crypto

#13658 feat: SMT Verificaiton Module: Data Structures
  barretenberg/cpp/src/barretenberg/smt_verification/README.md
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/circuit_base.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/circuit/ultra_circuit.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/solver/solver.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bool.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/bool.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/data_structures.hpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/data_structures.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/ffterm.test.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.cpp
  barretenberg/cpp/src/barretenberg/smt_verification/terms/term.hpp
Labels: product-security

#13760 feat!: Use combined p2p and http prover coordination
  spartan/aztec-network/templates/prover-node.yaml
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
  yarn-project/end-to-end/src/e2e_prover/e2e_prover_test.ts
  yarn-project/end-to-end/src/e2e_snapshot_sync.test.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/memory_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/tx_pool_test_suite.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/prover-node/src/config.ts
  yarn-project/prover-node/src/factory.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.test.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.ts
  yarn-project/prover-node/src/prover-coordination/config.ts
  yarn-project/prover-node/src/prover-coordination/factory.ts
  yarn-project/prover-node/src/prover-node.test.ts
  yarn-project/prover-node/src/prover-node.ts
  yarn-project/stdlib/src/interfaces/aztec-node.ts
  yarn-project/stdlib/src/interfaces/prover-coordination.ts
Labels: ci-full

#12993 feat: fuzzing docker image
  container-builds/fuzzing-container/.gitignore
  container-builds/fuzzing-container/run.sh
  container-builds/fuzzing-container/src/Dockerfile
  container-builds/fuzzing-container/src/entrypoint.sh
Labels: product-security

#13561 feat: A strict scheduler for tests/benchmarks. Currently not enabled.
  .github/workflows/ci3.yml
  .test_patterns.yml
  aztec-up/bin/.aztec-run
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/scripts/run_test_browser.sh
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/format.sh
  barretenberg/cpp/scripts/run_test.sh
  barretenberg/ts/bootstrap.sh
  bootstrap.sh
  boxes/bootstrap.sh
  boxes/docker-compose.yml
  boxes/scripts/run_test.sh
  build-images/src/Dockerfile
  build-images/src/docker_daemon.json
  ci.sh
  ci3/.gitignore
  ci3/aws_request_instance
  ci3/bootstrap_ec2
  ci3/cache_content_hash
  ci3/cpuset_count
  ci3/docker_isolate
  ci3/npm_install_deps
  ci3/parallelise
  ci3/parallelise_strict
  ci3/run_compose_test
  ci3/run_test_cmd
  ci3/sem_sched
  ci3/semc.c
  noir-projects/noir-contracts/bootstrap.sh
  noir/bootstrap.sh
  playground/docker-compose.yml
  spartan/bootstrap.sh
  yarn-project/aztec/docker-compose.yml
  yarn-project/bootstrap.sh
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/scripts/docker-compose.yml
  yarn-project/end-to-end/scripts/run_test.sh
  yarn-project/end-to-end/scripts/test_simple.sh
  yarn-project/end-to-end/src/composed/e2e_token_bridge_tutorial_test.test.ts
  yarn-project/end-to-end/src/e2e_fees/bridging_race.notest.ts
  yarn-project/ethereum/src/test/start_anvil.test.ts
  yarn-project/scripts/run_test.sh
Labels: ci-full
