Repository AztecProtocol/aztec-packages, pull requests merged in 2025-06, with the labels that each got.

#14690 chore: merge master into next manually
  .github/workflows/nightly-release-tag.yml
  .release-please-manifest.json
  CHANGELOG.md
  barretenberg/ts/src/log/node/index.ts
  docs/docs/aztec/concepts/advanced/storage/partial_notes.md
  docs/docs/developers/guides/smart_contracts/how_to_compile_contract.md
  docs/docs/developers/guides/smart_contracts/writing_contracts/storage/storage_slots.md
  l1-contracts/bootstrap.sh
  noir-projects/aztec-nr/aztec/src/macros/utils.nr
  noir-projects/noir-contracts/Nargo.toml
  noir-projects/noir-contracts/contracts/test/returning_tuple_contract/Nargo.toml
  noir-projects/noir-contracts/contracts/test/returning_tuple_contract/src/main.nr
  spartan/terraform/gke-cluster/snapshots.tf
  yarn-project/bootstrap.sh
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/foundation/src/config/index.ts
  yarn-project/p2p/src/client/interface.ts
  yarn-project/p2p/src/client/p2p_client.test.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/index.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.test.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/memory_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/tx_pool.ts
  yarn-project/p2p/src/msg_validators/msg_seen_validator/msg_seen_validator.test.ts
  yarn-project/p2p/src/msg_validators/msg_seen_validator/msg_seen_validator.ts
  yarn-project/p2p/src/services/dummy_service.ts
  yarn-project/p2p/src/services/index.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/batch_connection_sampler.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.ts
  yarn-project/p2p/src/services/reqresp/rate-limiter/rate_limiter.ts
  yarn-project/p2p/src/services/reqresp/rate-limiter/rate_limits.ts
  yarn-project/p2p/src/services/reqresp/reqresp.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
  yarn-project/p2p/src/services/service.ts
  yarn-project/p2p/src/services/tx_collector.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.ts
  yarn-project/pxe/src/contract_function_simulator/execution_data_provider.ts
  yarn-project/pxe/src/contract_function_simulator/oracle/oracle.ts
  yarn-project/pxe/src/contract_function_simulator/oracle/typed_oracle.ts
  yarn-project/pxe/src/contract_function_simulator/oracle/utility_execution_oracle.ts
  yarn-project/pxe/src/contract_function_simulator/pxe_oracle_interface.ts
  yarn-project/stdlib/src/abi/decoder.test.ts
  yarn-project/stdlib/src/abi/decoder.ts
  yarn-project/txe/src/oracle/txe_oracle.ts
  yarn-project/txe/src/state_machine/dummy_p2p_client.ts
  yarn-project/txe/src/txe_service/txe_service.ts
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
Labels: ci-full

#14717 fix: Only broadcast new txs
  yarn-project/p2p/src/client/interface.ts
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/client/p2p_client.test.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/memory_tx_pool.ts
  yarn-project/p2p/src/mem_pools/tx_pool/tx_pool.ts
  yarn-project/p2p/src/services/tx_collector.test.ts
  yarn-project/p2p/src/testbench/p2p_client_testbench_worker.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.test.ts
  yarn-project/prover-node/src/prover-coordination/combined-prover-coordination.ts
  yarn-project/txe/src/state_machine/dummy_p2p_client.ts
Labels: ci-external

#14773 chore: backport test
  .github/workflows/backport.yml
  CODEOWNERS
Labels: backport-to-master

#14756 feat: Limit the number of concurrent IVC verifiers
  yarn-project/aztec-node/src/aztec-node/server.ts
  yarn-project/bb-prover/src/config.ts
  yarn-project/bb-prover/src/test/test_verifier.ts
  yarn-project/bb-prover/src/verifier/bb_verifier.ts
  yarn-project/bb-prover/src/verifier/index.ts
  yarn-project/bb-prover/src/verifier/queued_ivc_verifier.ts
  yarn-project/end-to-end/src/bench/client_flows/data_extractor.ts
  yarn-project/end-to-end/src/fixtures/get_bb_config.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/foundation/src/queue/batch_queue.ts
  yarn-project/foundation/src/queue/serial_queue.test.ts
  yarn-project/foundation/src/queue/serial_queue.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/prover-client/src/config.ts
  yarn-project/prover-client/src/mocks/test_context.ts
  yarn-project/pxe/src/entrypoints/server/utils.ts
  yarn-project/stdlib/src/interfaces/server_circuit_prover.ts
Labels: ci-full

#14792 fix: Fixes the tracking of pending tx count
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_cursor.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_cursor.hpp
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_database.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/lmdb_store.test.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/queries.cpp
  barretenberg/cpp/src/barretenberg/lmdblib/queries.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/lmdb_store/lmdb_store_message.hpp
  barretenberg/cpp/src/barretenberg/nodejs_module/lmdb_store/lmdb_store_wrapper.cpp
  barretenberg/cpp/src/barretenberg/nodejs_module/lmdb_store/lmdb_store_wrapper.hpp
  yarn-project/kv-store/src/indexeddb/map.ts
  yarn-project/kv-store/src/interfaces/map.ts
  yarn-project/kv-store/src/interfaces/map_test_suite.ts
  yarn-project/kv-store/src/interfaces/multi_map_test_suite.ts
  yarn-project/kv-store/src/lmdb-v2/map.ts
  yarn-project/kv-store/src/lmdb-v2/message.ts
  yarn-project/kv-store/src/lmdb-v2/multi_map.ts
  yarn-project/kv-store/src/lmdb-v2/read_transaction.ts
  yarn-project/kv-store/src/lmdb/map.ts
  yarn-project/p2p/src/mem_pools/tx_pool/aztec_kv_tx_pool.ts
Labels: ci-full, backport-to-master

#14784 chore: disable AVM build on ARM64
  barretenberg/cpp/bootstrap.sh
  barretenberg/cpp/scripts/compile_avm.sh
  barretenberg/cpp/scripts/rebuild_avm.sh
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  yarn-project/aztec/src/cli/cmds/start_prover_agent.ts
  yarn-project/aztec/src/cli/cmds/start_prover_node.ts
  yarn-project/bootstrap.sh
  yarn-project/end-to-end/bootstrap.sh
  yarn-project/end-to-end/src/e2e_prover/client.test.ts
Labels: ci-full

#14859 chore: reenable prover-full
  .test_patterns.yml
Labels: ci-full

#14843 chore: Properly separate ci runs into master/next/releases.
  .github/workflows/backport.yml
  ci.sh
  ci3/log_ci_run
  ci3/run_test_cmd
  ci3/source_color
  ci3/source_refname
Labels: backport-to-master

#14887 chore: add browser flakes
  .test_patterns.yml
  ci3/get_test_owner
  ci3/log_ci_run
  ci3/run_test_cmd
Labels: backport-to-master

#14797 feat: hide commitments and evaluations in (most of) the wires in translator
  barretenberg/cpp/src/barretenberg/polynomials/polynomial.test.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations.cpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_extra_relations_impl.hpp
  barretenberg/cpp/src/barretenberg/relations/translator_vm/translator_relation_consistency.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/relation_correctness.test.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_fixed_vk.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.cpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_proving_key.hpp
  noir-projects/noir-protocol-circuits/bootstrap.sh
Labels: ci-full

#14452 feat!: Fiat-Shamir the vk
  .test_patterns.yml
  barretenberg/cpp/scripts/test_civc_standalone_vks_havent_changed.sh
  barretenberg/cpp/src/barretenberg/boomerang_value_detection/graph.cpp
  barretenberg/cpp/src/barretenberg/boomerang_value_detection/graph_description_ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/commitment_schemes/pairing_points.hpp
  barretenberg/cpp/src/barretenberg/ecc/fields/field_conversion.hpp
  barretenberg/cpp/src/barretenberg/eccvm/eccvm_flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor.hpp
  barretenberg/cpp/src/barretenberg/flavor/flavor_concepts.hpp
  barretenberg/cpp/src/barretenberg/honk/execution_trace/mega_execution_trace.hpp
  barretenberg/cpp/src/barretenberg/stdlib/eccvm_verifier/eccvm_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib/hash/poseidon2/poseidon2.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/oink_recursive_verifier.cpp
  barretenberg/cpp/src/barretenberg/stdlib/honk_verifier/ultra_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/circuit_builders/circuit_builders_fwd.hpp
  barretenberg/cpp/src/barretenberg/stdlib/primitives/padding_indicator_array/padding_indicator_array.hpp
  barretenberg/cpp/src/barretenberg/stdlib/protogalaxy_verifier/protogalaxy_recursive_verifier.test.cpp
  barretenberg/cpp/src/barretenberg/stdlib/translator_vm_verifier/translator_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/mega_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.cpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_circuit_builder.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_keccak_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_rollup_flavor.hpp
  barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/ultra_rollup_recursive_flavor.hpp
  barretenberg/cpp/src/barretenberg/trace_to_polynomials/trace_to_polynomials.hpp
  barretenberg/cpp/src/barretenberg/transcript/transcript.hpp
  barretenberg/cpp/src/barretenberg/translator_vm/translator_flavor.hpp
  barretenberg/cpp/src/barretenberg/ultra_honk/mega_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_prover.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/oink_verifier.cpp
  barretenberg/cpp/src/barretenberg/ultra_honk/ultra_transcript.test.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.cpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/flavor.hpp
  barretenberg/cpp/src/barretenberg/vm2/constraining/recursion/recursive_flavor.hpp
  yarn-project/end-to-end/bootstrap.sh
Labels: ci-full

#15001 fix(bb.js): don't set maximum wasm memory >1GB on ios web, limit SRS
  barretenberg/ts/src/barretenberg/index.ts
  barretenberg/ts/src/barretenberg_wasm/barretenberg_wasm_main/index.ts
Labels: backport-to-master

#14900 fix: p2p qol fixes
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/peer-manager/peer_manager.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.test.ts
  yarn-project/p2p/src/services/reqresp/connection-sampler/connection_sampler.ts
  yarn-project/p2p/src/services/reqresp/protocols/status.ts
  yarn-project/p2p/src/services/reqresp/reqresp.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
Labels: ci-external

#14983 refactor(slash)!: Make slashing function bounded by available balance
  .test_patterns.yml
  l1-contracts/src/core/libraries/staking/StakingLib.sol
  l1-contracts/test/staking/slash.t.sol
Labels: ci-external

#14985 feat: optimize `create_stub_base` to use arrays instead of slices
  noir-projects/aztec-nr/aztec/src/macros/functions/call_interface_stubs.nr
  noir-projects/aztec-nr/aztec/src/macros/utils.nr
Labels: ci-full

#15045 fix(box): remove codegenCache during clean
  boxes/boxes/react/package.json
  boxes/boxes/vite/package.json
Labels: backport-to-master

#14870 fix: Receipt transaction hash mismatch
  .test_patterns.yml
  yarn-project/end-to-end/src/e2e_epochs/epochs_l1_reorgs.test.ts
  yarn-project/end-to-end/src/e2e_epochs/epochs_test.ts
  yarn-project/end-to-end/src/fixtures/l1_to_l2_messaging.ts
  yarn-project/end-to-end/src/fixtures/utils.ts
  yarn-project/ethereum/src/eth_cheat_codes.ts
  yarn-project/ethereum/src/test/chain_monitor.ts
  yarn-project/prover-client/src/proving_broker/proving_broker.ts
Labels: ci-full

#15068 chore: update to jest30
  barretenberg/ts/package.json
  barretenberg/ts/yarn.lock
  yarn-project/accounts/package.json
  yarn-project/archiver/package.json
  yarn-project/aztec-faucet/package.json
  yarn-project/aztec-node/package.json
  yarn-project/aztec.js/package.json
  yarn-project/aztec/package.json
  yarn-project/bb-prover/package.json
  yarn-project/blob-lib/package.json
  yarn-project/blob-sink/package.json
  yarn-project/bot/package.json
  yarn-project/builder/package.json
  yarn-project/cli-wallet/package.json
  yarn-project/cli/package.json
  yarn-project/constants/package.json
  yarn-project/end-to-end/package.json
  yarn-project/end-to-end/src/e2e_token_contract/transfer_in_private.test.ts
  yarn-project/end-to-end/src/e2e_token_contract/transfer_in_public.test.ts
  yarn-project/entrypoints/package.json
  yarn-project/epoch-cache/package.json
  yarn-project/ethereum/package.json
  yarn-project/foundation/package.json
  yarn-project/foundation/src/crypto/sha256/index.test.ts
  yarn-project/ivc-integration/package.json
  yarn-project/key-store/package.json
  yarn-project/kv-store/package.json
  yarn-project/merkle-tree/package.json
  yarn-project/native/package.json
  yarn-project/node-lib/package.json
  yarn-project/noir-bb-bench/package.json
  yarn-project/noir-contracts.js/package.json
  yarn-project/noir-protocol-circuits-types/package.json
  yarn-project/noir-test-contracts.js/package.json
  yarn-project/p2p-bootstrap/package.json
  yarn-project/p2p/package.json
  yarn-project/package.common.json
  yarn-project/protocol-contracts/package.json
  yarn-project/prover-client/package.json
  yarn-project/prover-node/package.json
  yarn-project/pxe/package.json
  yarn-project/sequencer-client/package.json
  yarn-project/simulator/package.json
  yarn-project/simulator/src/public/avm/opcodes/environment_getters.test.ts
  yarn-project/slasher/package.json
  yarn-project/stdlib/package.json
  yarn-project/telemetry-client/package.json
  yarn-project/txe/package.json
  yarn-project/validator-client/package.json
  yarn-project/world-state/package.json
  yarn-project/yarn.lock
Labels: ci-full

#15076 chore: Benchmarks for LMDB stores
  yarn-project/bootstrap.sh
  yarn-project/kv-store/.mocharc.json
  yarn-project/kv-store/package.json
  yarn-project/kv-store/src/bench/map_bench.test.ts
  yarn-project/kv-store/src/indexeddb/map.ts
  yarn-project/kv-store/src/interfaces/map.ts
  yarn-project/kv-store/src/interfaces/map_test_suite.ts
  yarn-project/kv-store/src/lmdb-v2/map.ts
  yarn-project/kv-store/src/lmdb-v2/multi_map.ts
  yarn-project/kv-store/src/lmdb/map.ts
Labels: ci-full

#14858 feat: set zero knowledge to be the default in `bb-cli`
  .test_patterns.yml
  barretenberg/acir_tests/bootstrap.sh
  barretenberg/acir_tests/flows/bb_prove_bbjs_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_bb_verify.sh
  barretenberg/acir_tests/flows/bbjs_prove_sol_verify.sh
  barretenberg/acir_tests/flows/prove_then_verify.sh
  barretenberg/acir_tests/flows/sol_honk.sh
  barretenberg/acir_tests/flows/sol_honk_zk.sh
  barretenberg/acir_tests/internal_test_programs/double_verify_honk_zk_proof/Nargo.toml
  barretenberg/acir_tests/internal_test_programs/double_verify_honk_zk_proof/src/main.nr
  barretenberg/acir_tests/internal_test_programs/verify_honk_zk_proof/Nargo.toml
  barretenberg/acir_tests/internal_test_programs/verify_honk_zk_proof/src/main.nr
  barretenberg/acir_tests/sol-test/src/index.js
  barretenberg/cpp/src/barretenberg/api/api.hpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.cpp
  barretenberg/cpp/src/barretenberg/api/api_ultra_honk.hpp
  barretenberg/cpp/src/barretenberg/bb/cli.cpp
  noir-projects/noir-protocol-circuits/bootstrap.sh
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/prover/server/bb_prover.ts
  yarn-project/ivc-integration/src/prove_native.ts
Labels: ci-full

#14921 chore: Limit IVC verification concurrency
  yarn-project/bb-prover/src/bb/execute.ts
  yarn-project/bb-prover/src/config.ts
  yarn-project/bb-prover/src/verifier/bb_verifier.ts
  yarn-project/end-to-end/src/bench/client_flows/data_extractor.ts
  yarn-project/end-to-end/src/fixtures/get_bb_config.ts
  yarn-project/foundation/src/config/env_var.ts
  yarn-project/prover-client/src/config.ts
  yarn-project/prover-client/src/mocks/test_context.ts
  yarn-project/pxe/src/entrypoints/server/utils.ts
Labels: ci-full

#15128 fix: bump archiver and WS schema versions
  yarn-project/archiver/src/archiver/kv_archiver_store/kv_archiver_store.ts
  yarn-project/world-state/src/native/native_world_state.ts
Labels: backport-to-master

#15156 chore: introduce staging branch
  .github/release-please-staging.json
  .github/workflows/ci3-external.yml
  .github/workflows/release-please.yml
  ci3/run_test_cmd
Labels: backport-to-master, backport-to-staging

#15162 fix: Handle spot eviction from host, not container.
  barretenberg/acir_tests/bootstrap.sh
  ci3/aws_handle_evict
  ci3/bootstrap_ec2
Labels: backport-to-staging

#15188 fix: run shout tests on staging
  .backportrc.json
  ci3/run_test_cmd
  l1-contracts/bootstrap.sh
  l1-contracts/test/shouting.t.sol
  yarn-project/aztec/src/test/testnet_compatibility.test.ts
  yarn-project/bootstrap.sh
Labels: backport-to-staging

#15229 fix: p2p private key value
  yarn-project/foundation/src/config/index.ts
  yarn-project/p2p/src/bootstrap/bootstrap.ts
  yarn-project/p2p/src/client/factory.ts
  yarn-project/p2p/src/config.ts
  yarn-project/p2p/src/test-helpers/reqresp-nodes.ts
  yarn-project/p2p/src/testbench/worker_client_manager.ts
  yarn-project/p2p/src/util.test.ts
  yarn-project/p2p/src/util.ts
Labels: backport-to-staging

#15269 chore: Alpha tx pool size reduced back
  yarn-project/aztec/src/cli/chain_l2_config.ts
Labels: backport-to-staging

#15284 fix: Wait for archiver to be synced when attesting
  yarn-project/validator-client/src/validator.test.ts
  yarn-project/validator-client/src/validator.ts
Labels: ci-full, backport-to-staging

#15356 fix: PXE batch block limit
  yarn-project/end-to-end/src/bench/utils.ts
  yarn-project/pxe/src/config/index.ts
  yarn-project/pxe/src/entrypoints/client/bundle/utils.ts
  yarn-project/pxe/src/entrypoints/client/lazy/utils.ts
  yarn-project/pxe/src/entrypoints/server/utils.ts
  yarn-project/pxe/src/test/pxe_service.test.ts
  yarn-project/stdlib/src/block/l2_block_stream/l2_block_stream.ts
Labels: backport-to-master, backport-to-staging

#15371 chore: removed sendRequest
  yarn-project/end-to-end/src/spartan/1tps.test.ts
  yarn-project/p2p/src/client/interface.ts
  yarn-project/p2p/src/client/p2p_client.integration.test.ts
  yarn-project/p2p/src/client/p2p_client.ts
  yarn-project/p2p/src/services/libp2p/libp2p_service.ts
  yarn-project/p2p/src/services/reqresp/interface.ts
  yarn-project/p2p/src/services/reqresp/reqresp.test.ts
  yarn-project/p2p/src/services/reqresp/reqresp.ts
  yarn-project/p2p/src/services/service.ts
  yarn-project/validator-client/src/validator.test.ts
Labels: ci-external, ci-full

#15084 chore: proving broker benchmarks
  yarn-project/bootstrap.sh
  yarn-project/prover-client/src/proving_broker/proving_broker.ts
  yarn-project/prover-client/src/test/mock_proof_store.ts
  yarn-project/prover-client/src/test/proving_broker_testbench.test.ts
Labels: ci-external
